### ISSUE TITLE
SendCaptureStoppedEvent Should be virtual

### ISSUE THREAD

**Issue by Abdullah2993** [chmorgan/sharppcap#10]
[SendCaptureStoppedEvent](https://github.com/chmorgan/sharppcap/blob/master/SharpPcap/LibPcap/PcapDevice.cs#L273) should be marked as `virtual` just like [SendPacketArrivalEvent](https://github.com/chmorgan/sharppcap/blob/master/SharpPcap/LibPcap/PcapDevice.cs#L257)

**Comment by chmorgan** [comment]
Fixed pushed up.
