### ISSUE TITLE
Packet Manipulation

### ISSUE THREAD

**Issue by njbrown09** [chmorgan/sharppcap#108]
Im trying to manipulate a UDP packet inside a PPTP packet. It doesnt seem to be working, am i doing something wrong?

PPTP VPN Packet -extract> UdpPacket -extract> DestinationPacket = something different.

**Comment by chmorgan** [comment]
Can you show an example of the code that isn't working as expected?

**Comment by chmorgan** [comment]
Closing due to lack of response. Please reopen if you still have this question!
