### ISSUE TITLE
Can I capture it remotely?

### ISSUE THREAD

**Issue by bbhxwl** [chmorgan/sharppcap#118]
Can I capture it remotely?

**Comment by chmorgan** [comment]
Hi @bbhxwl. If winpcap or npcap or libpcap (depending on your platform) then yep. See https://github.com/chmorgan/sharppcap/tree/master/Examples/NpcapRemoteCapture

**Comment by chmorgan** [comment]
@bbhxwl, @kayoub5 mentioned that npcap remote capture support may not be functional at the moment. Are you trying to capture remotely using npcap?

**Comment by bbhxwl** [comment]
thank you
