### ISSUE TITLE
Question about e.Packet.Timeval.Date

### ISSUE THREAD

**Issue by landws** [chmorgan/sharppcap#121]
what's the e.Packet.Timeval.Date  exactly means?  when OnPacketArrival triggered, i print this datetime and DateTime.Now, output as below, formatter is HH:mm:ss.fff

08:13:03.480 [ACK][1734913729] Len=298
16:13:04.211 [ACK][1734913729] internel ip -> myip Payload Length:232

 line1 is Timeval.Date, line2 is DateTime.Now, what is the lag between them? thanks
btw, pls ingore the hour part, my timezone is GMT+8

@chmorgan

**Comment by kayoub5** [comment]
It's the time the packet was captured by the driver, packets remain queued up to `read_timeout` in order to reduce overhead on OS kernel, you can set this to 0 to receive packets as fast as possible.

Another reason were delays could happen is that if the handler code of `OnPacketArrival` takes too long, than packets will have to be queued for even longer duration.

**Comment by chmorgan** [comment]
@landws can you comment on what is in your OnPacketArrival handler and what computing system you are running on? You should expect to see extremely low latency when capturing on a modern multi-core multi-gigahertz system.

**Comment by landws** [comment]
@kayoub5 thanks 

@chmorgan  here is my code and output, my running environment is 

OS & Runtime: Windows 10 1909 (18363.778) /  .NET 4.7.2 / VS2017 15.9.22 / MS Build 15
Driver: Npcap 0.9986 
CPU: Inter Core i5-3470T @ 2.9GH 4 cores
MEM:  8G Memeory
Network card: Intel(R) 82579LM Gigabit Network Connection

        private void device_OnPacketArrival(object sender, CaptureEventArgs e)
        {
            var packet = PacketDotNet.Packet.ParsePacket(e.Packet.LinkLayerType, e.Packet.Data);
            var tcpPacket = packet.Extract<PacketDotNet.TcpPacket>();
            if (tcpPacket != null)
            {
                if (tcpPacket.PayloadData == null || tcpPacket.PayloadData.Length <= 0) return;

                if (Program.IsLocalDebug())
                {
                    var time = e.Packet.Timeval.Date;
                    var len = e.Packet.Data.Length;
                    var ack = tcpPacket.AcknowledgmentNumber;
                    Console.WriteLine("{0} [ACK][{1}] Len={2}", time.ToString("HH:mm:ss.fff"), ack, len);
                    Console.WriteLine("{0} {1}", DateTime.Now.ToString("HH:mm:ss.fff"), DateTime.Now.Subtract(time.AddHours(8)).TotalMilliseconds);
                }
                queue.Enqueue(tcpPacket);
            }
        }

output:

09:54:05.657 [ACK][3156214534] Len=298
17:54:06.158 501.1777

**Comment by chmorgan** [comment]
I’d recommend not printing in the callback as printing can take some amount
of time. If you queue the packets and print them out from another thread do
you see timing that matches what you’d expect to see?

Chris

**Comment by landws** [comment]
Unfortunately, seems no better
 the callback only put the raw packets in a queue, and print out in another thread

print thread:

Console.WriteLine("{0} [ACK][{1}] Len={2}", time.ToString("HH:mm:ss.fff"), ack, len);
Console.WriteLine("{0} {1}", DateTime.Now.ToString("HH:mm:ss.fff"), DateTime.Now.Subtract(time.AddHours(8)).TotalMilliseconds);

output:

07:44:47.955 [ACK][1299981332] Len=200
15:44:48.747 791.161
07:44:48.969 [ACK][1299981332] Len=200
15:44:49.747 777.4616
07:44:49.559 [ACK][4190478578] Len=128
15:44:49.747 188.0296
07:44:49.984 [ACK][1299981394] Len=200
15:44:50.747 762.7896
07:44:50.997 [ACK][1299981394] Len=200
15:44:51.748 751.1769
07:44:52.011 [ACK][1299981394] Len=200

**Comment by landws** [comment]
> read_timeout
sniffer looks like has stuck after set read_timeout to 0, so, i try to set read_timeout from 1000 to 500, the lag seems to be smaller, it looks always less than read_timeout

localdevice.Open(DeviceMode.Promiscuous, read_timeout);

**Comment by kayoub5** [comment]
@landws you can set the read timeout to 1ms

**Comment by landws** [comment]
> @landws you can set the read timeout to 1ms

indeed, it works. thank you, question closed.
