### ISSUE TITLE
OnPacketArrival data 0 length

### ISSUE THREAD

**Issue by asaadmohammed74** [chmorgan/sharppcap#131]
im trying to capture packets using StartCapture/OnPacketArrival but right now i only get data with 0 length. tried with WinPcap, LibPcap, Npcap all give the same result.

event:
`
        private void Device_OnPacketArrival(object sender, SharpPcap.CaptureEventArgs e) {
            var rawCapture = e.Packet;
            Console.WriteLine(rawCapture.Data.Length); // always 0
        }
`

load:
`
        private void MainForm_Load(object sender, EventArgs e) {
            var device = SharpPcap.LibPcap.LibPcapLiveDeviceList.Instance.Where(x => x.Description == "Broadcom NetLink (TM) Gigabit Ethernet Driver").First();
            device.Open();
            Console.WriteLine(device.MacAddress); // print the mac of Local Area Connection
            device.OnPacketArrival += Device_OnPacketArrival;
            device.Capture();
        }
`

**Comment by wangfu91** [comment]
I've encountered the same issue, after upgrade Npcap to the latest version 0.9994, the problem no longer occurs.

**Comment by chmorgan** [comment]
Closing out as it appears to be resolved by a newer npcap version.
