### ISSUE TITLE
PosixTimeval.cs incorrect Microsecond output from ToString()

### ISSUE THREAD

**Issue by bucweat** [chmorgan/sharppcap#14]
In sharppcap/SharpPcap/PosixTimeval.cs, line 271: method sb.Append(MicroSeconds); is incorrect for values of MicroSeconds < 100000. For example, for seconds = 1 and Microseconds = 12345, resulting value returned by ToString() is 1.12345. It should be 1.012345.

Solution is to replace line 271 
    sb.Append(MicroSeconds);
with 
    sb.AppendFormat("{0:000000}",MicroSeconds);

**Comment by chmorgan** [comment]
Added a unit test and pushed this out just a second ago. Thank you again for reporting it.
