### ISSUE TITLE
I failed to capture him in Linux?

### ISSUE THREAD

**Issue by bbhxwl** [chmorgan/sharppcap#146]
I failed to capture him in Linux?

Nuget installation SharpPcap.Core
The error is as follows. Why?

[root@VM-4-2-centos test]# dotnet ConsoleApp8.dll
SharpPcap 1.0.0.0, Example1.IfList.cs
Unhandled exception. System.DllNotFoundException: Unable to load shared library 'wpcap' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libwpcap: cannot open shared object file: No such file or directory
   at SharpPcap.LibPcap.LibPcapSafeNativeMethods.pcap_findalldevs(IntPtr& alldevs, StringBuilder errbuf)
   at SharpPcap.LibPcap.LibPcapLiveDeviceList.GetDevices()
   at SharpPcap.LibPcap.LibPcapLiveDeviceList.Refresh()
   at SharpPcap.LibPcap.LibPcapLiveDeviceList..ctor()
   at SharpPcap.LibPcap.LibPcapLiveDeviceList.get_Instance()
   at SharpPcap.CaptureDeviceList..ctor()
   at SharpPcap.CaptureDeviceList.get_Instance()
   at ConsoleApp8.Program.Main(String[] args) in D:\ImportantProject\ConsoleApp8\Program.cs:line 16
Aborted

 static void Main(string[] args)
        {

            // Print SharpPcap version
            string ver = SharpPcap.Version.VersionString;
            Console.WriteLine("SharpPcap {0}, Example1.IfList.cs", ver);

            // Retrieve the device list
            var devices = CaptureDeviceList.Instance;

            // If no devices were found print an error
            if (devices.Count < 1)
            {
                Console.WriteLine("No devices were found on this machine");
                return;
            }

            Console.WriteLine("\nThe following devices are available on this machine:");
            Console.WriteLine("----------------------------------------------------\n");

            /* Scan the list printing every entry */
            foreach (var dev in devices)
                Console.WriteLine("{0}\n", dev.ToString());

            Console.Write("Hit 'Enter' to exit...");
            Console.ReadLine();

        }

**Comment by bbhxwl** [comment]
Libpcapalivedevicelist doesn't work either.

**Comment by chmorgan** [comment]
That doesn't look at all like the correct version of SharpPcap, can you get info on which nuget package is installed?

**Comment by bbhxwl** [comment]
> That doesn't look at all like the correct version of SharpPcap, can you get info on which nuget package is installed?

There was a download error. It's a pirated one.

**Comment by chmorgan** [comment]
I’m not following. Does it work with the actual latest sharppcap release?
Why would you pirate open source software :-)

**Comment by kayoub5** [comment]
@chmorgan I think he installed https://www.nuget.org/packages/SharpPcap.Core/ by mistake.

**Comment by chmorgan** [comment]
That makes a sense.

I sent a message to the author of that package asking them to drop it from
the nuget store due to confusion and support of core in mainline.

Chris

**Comment by bbhxwl** [comment]
> @chmorgan I think he installed https://www.nuget.org/packages/SharpPcap.Core/ by mistake.

yes
