### ISSUE TITLE
Why can  LibPcapLiveDevice be used in windows?

### ISSUE THREAD

**Issue by bbhxwl** [chmorgan/sharppcap#149]
Why can LibPcapLiveDevice be used in windows?

 SharpPcap.LibPcap.LibPcapLiveDeviceList
SharpPcap.WinPcap.WinPcapDeviceList
SharpPcap.CaptureDeviceList

What's the difference between these three? I run httpmonitor example, which uses libpcapalivedevice, but can also intercept data normally. Why?

**Comment by bbhxwl** [comment]
static void HandleTcpConnectionManagerOnConnectionFound (TcpConnection c)
        {
            var httpSessionWatcher = new HttpSessionWatcher(c,
                                                            OnHttpRequestFound,
                                                            OnHttpStatusFound,
                                                            OnHttpWatcherError);
             
        }


For httpmonitor example, only OnHttpRequestFound. No OnHttpResponseFound

**Comment by bbhxwl** [comment]
Your SharpPcap is really a good thing. It seems that only C + + is good at this project. Thank you for developing this thing, so that we can use C#

**Comment by chmorgan** [comment]
You can work one level down, use the tcp flow class, that’s what the http
classes use internally.

**Comment by bbhxwl** [comment]
static void HandleTcpConnectionManagerOnConnectionFound (TcpConnection c)
        {
            (new TcpFlow(,)).OnPacketReceived += MainClass_OnPacketReceived; ;
             var httpSessionWatcher = new HttpSessionWatcher(c,
                                                            OnHttpRequestFound,
                                                            OnHttpStatusFound,
                                                            OnHttpWatcherError);
        }

        private static void MainClass_OnPacketReceived(PosixTimeval timeval, TcpPacket tcp, TcpConnection connection, TcpFlow flow)
        {
             
        }

**Comment by bbhxwl** [comment]
I don't know how to write the code?

**Comment by bbhxwl** [comment]
Can httpmonitorexample add request and response?

**Comment by bbhxwl** [comment]
The wiki does not have any documentation.

**Comment by chmorgan** [comment]
Yeah TcpFlow is the class you want to use.

All of the classes have documentation on themselves and each method. I’d
review how the http code does it and model after that approach.

**Comment by bbhxwl** [comment]
> Yeah TcpFlow is the class you want to use. All of the classes have documentation on themselves and each method. I’d review how the http code does it and model after that approach.
> […](#)

I may be too stupid to use tcpflow, and I don't know where to use this class. I am a Chinese, English depends on translation software, hope to help me, give me an example.

**Comment by bbhxwl** [comment]
There are two each time. Is there a request and a response?

   
static void HandleTcpConnectionManagerOnConnectionFound (TcpConnection c)
        {
            Console.WriteLine(c.Flows.Count);
 
        }

**Comment by bbhxwl** [comment]
There are two each time. Is there a request and a response?
`static void HandleTcpConnectionManagerOnConnectionFound (TcpConnection c)
{
Console.WriteLine(c.Flows.Count);

 }`

**Comment by bbhxwl** [comment]
static void HandleTcpConnectionManagerOnConnectionFound (TcpConnection c)
       
 {

            Console.WriteLine(c.Flows.Count);
         
        }

        private static void MainClass_OnPacketReceived(PosixTimeval timeval, TcpPacket tcp, TcpConnection connection, TcpFlow flow)
        {
         
        }

**Comment by bbhxwl** [comment]
static void HandleTcpConnectionManagerOnConnectionFound (TcpConnection c)
        {
            c.Flows[0].OnPacketReceived += MainClass_OnPacketReceived;
            Console.WriteLine(c.Flows.Count);
               //var httpSessionWatcher = new HttpSessionWatcher(c,
               //                                             OnHttpRequestFound,
               //                                             OnHttpStatusFound,
               //                                             OnHttpWatcherError);
        }

        private static void MainClass_OnPacketReceived(PosixTimeval timeval, TcpPacket tcp, TcpConnection connection, TcpFlow flow)
        {
         
        }

**Comment by bbhxwl** [comment]
Is that so?

**Comment by chmorgan** [comment]
Yep, the TcpConnectionManager will let you know when new connections are
found. I’d recommend trying out the http examples to see how they work and
add some prints around or breakpoints in the debugger.

**Comment by bbhxwl** [comment]
> Yep, the TcpConnectionManager will let you know when new connections are found. I’d recommend trying out the http examples to see how they work and add some prints around or breakpoints in the debugger.
> […](#)


I have seen the HTTP instance, and I think the response should also be a delegate or an event. But it hasn't been found. If only one could be written in the example.

**Comment by chmorgan** [comment]
Hi @bbhxwl. Did you figure this out eventually?

**Comment by bbhxwl** [comment]
> Hi @bbhxwl. Did you figure this out eventually?

yes

**Comment by chmorgan** [comment]
Closing this out as its a question of understanding the class and its methods.
