### ISSUE TITLE
Ready to push a new version to nuget?

### ISSUE THREAD

**Issue by chmorgan** [chmorgan/sharppcap#150]
@kayoub5 think we are ready to bump the version up so the nuget version is updated?

**Comment by kayoub5** [comment]
I believe so

**Comment by chmorgan** [comment]
@kayoub5 do you have any idea about appveyor.yml? I was trying to get packetnet-connections to properly push to nuget and I refreshed the expired nuget key for sharppcap and figured I'd turn off the ui options as the Appveyor.yml should take precedence and now I can't get Appveyor to push. It's seriously a huge pain in the ass...

**Comment by chmorgan** [comment]
Done!
