### ISSUE TITLE
Example02.ArpResolve not work well

### ISSUE THREAD

**Issue by Wahitler** [chmorgan/sharppcap#152]
Example02.ArpResolve Target Framework is 4.6.1，it doesnet work

![QQ截图20200811094802](https://user-images.githubusercontent.com/12858618/89847984-ebd00c80-dbb7-11ea-88d4-f2c488bd4a4a.png)

if change target framework to dotnetcore2.0 ,it work well

**Comment by zpaul48** [comment]
it doesn't work on both of frameworks. The value of enumeration device.Addresses can not  retrieve adapter's mac address. 
Win10 is installed on my computer. I also installed npcap 0.9997 on it.

**Comment by chmorgan** [comment]
@Wahitler can you capture what the content of _device.Addresses is above and paste it here?

**Comment by zpaul48** [comment]
[
![image](https://user-images.githubusercontent.com/48132479/91928725-5b48a000-ed0f-11ea-8f46-ecb62432f58e.png)
](url)

The interface associated with this device object is a wireless connection。
When I execute _ipconfig_ command, the output of the connection is as follows:
[
![image](https://user-images.githubusercontent.com/48132479/91929795-cb582580-ed11-11ea-9941-89fc2966799f.png)
](url)
My adapter is Intel(R) Wi-Fi 6 AX200 160MHz

**Comment by chmorgan** [comment]
@zpaul48 can you expand so we can see the value of Addr.type?

See the code above the if(localMAC == NULL) that checks the type to see if its a local address, I'm trying to see what type the adapters actually are.

Maybe we can't use the type like we are trying to....

**Comment by zpaul48** [comment]
[
![image](https://user-images.githubusercontent.com/48132479/92061793-c191f900-edc9-11ea-9b53-9dfcf4424f8c.png)
](url)

**Comment by chmorgan** [comment]
can you look at the ipAddress.AddressFamily values? That's the other check in the code for local addresses.

**Comment by zpaul48** [comment]
I think that's not the point. (*^_^*)
To return all network interfaces, sharppcap sourcecode call a function named **pcap_findalldevs(ref IntPtr alldevs, StringBuilder  errbuf)**  in wpcap.dll, but the MAC address information is not included in the returned result.
Alternatively, I think we can get the physical address of a interface just like the gateway address.
It's obtained from System.Net.NetworkInformation.NetworkInterface.

**Comment by chmorgan** [comment]
@zpaul48 I'm flying blind here as I'm not using windows. Are you using winpcap and not npcap? You should probably be using npcap if you can. I'm pretty sure I had tested this out before putting the code back, its not typical for us to ship without testing but perhaps its a bug or something changed?

If we can use System.Net.NetworkInformation.NetworkInterface would you be able to modify the code to correct the issue?

**Comment by narajikimi86** [comment]
I also collection device.Addresses doesn't contain adapter's mac address.
With the same conditions, it was done in SharpPcap 5.0.
However, it does not work after updating to 5.2.
[win10, .netstandard2.0, npcap 0.9994]

**Comment by zpaul48** [comment]
@narajikimi86 
Where can I get SharpPcap 5.0?
I can only find v5.2 and v4.3 on github.

**Comment by narajikimi86** [comment]
@zpaul48 
I get it from VisualStudio.
You can get it through Nuget Package in VisualStudio.

**Comment by zpaul48** [comment]
How can I get the source code of v5.0? I'll want to compare the difference between 5.2 and 5.0.  @chmorgan

**Comment by zpaul48** [comment]
I had fixed this issue after I referred to the source code of 5.0. and how can I update the code on GitHub? @chmorgan 

[PcapInterface.cs.txt](https://github.com/chmorgan/sharppcap/files/5208482/PcapInterface.cs.txt)

**Comment by chmorgan** [comment]
Hi @zpaul48. Can you submit a pull request? I can't tell what you changed here.

**Comment by zpaul48** [comment]
I submitted the change，but test routine of macos failed. and I have no macos to test my code. @chmorgan

**Comment by chmorgan** [comment]
@zpaul48 @Wahitler @narajikimi86 can you check to see if https://github.com/chmorgan/sharppcap/pull/160 branch works?

**Comment by chmorgan** [comment]
I think this is fixed and released so I'm closing it out now.
