### ISSUE TITLE
CaptureDeviceList.New (System.IndexOutOfRangeException: Index was outside the bounds of the array.)

### ISSUE THREAD

**Issue by Shadow4walker** [chmorgan/sharppcap#154]
i need to use two new instance of ICaptureDevice
and i'm initialize it like so 

>var ins = CaptureDeviceList.Instance;
ins.Refresh();
var firstDevice=CaptureDeviceList.New()["Ethernet"];//this code giving "System.IndexOutOfRangeException: Index was outside the bounds of the array."!!

instead below code is working
>var deviceInt = ins.FindIndex(x => ((LibPcapLiveDevice) x).Interface.FriendlyName.Equals("Ethernet"));
var firstDevice= CaptureDeviceList.New()[deviceInt];
var SecondDevice= CaptureDeviceList.New()[deviceInt]

but using  CaptureDeviceList.New() is taking so many time to finish and also the the device macAddress is null!!
how i can initialize it properly without taking so much time?

**Comment by chmorgan** [comment]
The Mac address issue should be resolved in the forthcoming 5.3 release.

The cause of your above issue is that LibPcapLiveDeviceList[] and NpcapDeviceList[] look at the Name and Description fields of the interfaces, not the FriendlyName. Eg. if you had used something like "en0" that would work but "Ethernet" might not.

It might make sense to also look at the FriendlyName field. Thoughts on whether or why that would be a good idea? Are FriendlyNames unique?


On the capture list creation time:

I'm pretty sure the delay is unrelated to SharpPcap, that's how long it takes the underlying library npcap/winpcap/libpcap to find the devices. Afaik there would be no reason for us to introduce any kind of artificial delay in that pinvoke call chain.

Have you tried with the latest version of npcap? I presume you are on Windows. You could report the question to them.

**Comment by kayoub5** [comment]
@chmorgan the delay could also be caused by `NetworkInterface.GetAllNetworkInterfaces()`, that function is slow and can take up to 50ms on windows.

**Comment by chmorgan** [comment]
@kayoub5 we could lazy acquire the addresses to avoid that delay. @Shadow4walker how long is the delay you are seeing? Can you explain why it is an issue for your particular use case?

**Comment by kayoub5** [comment]
@Shadow4walker you could do `new LibPcapLiveDevice(((LibPcapLiveDevice) x).Interface)` that way no devices refresh will be performed.

**Comment by Shadow4walker** [comment]
hello @chmorgan @kayoub5  sorry for the late reply the issue has been fixed after using Npcap latest version as the following

> var npInterface = NpcapDeviceList.Instance.First(x => x.Interface.FriendlyName.Equals(DeviceUniqueFriendlyName)).Interface;
                        FirstDevice= new NpcapDevice(npInterface);
                        SecondDevice= new NpcapDevice(npInterface); 

Thanks for your Feedback.
