### ISSUE TITLE
Is there any chance to implement WinDivert.SentPacket sooner?

### ISSUE THREAD

**Issue by BarbaTunnelCoder** [chmorgan/sharppcap#156]
I have got so happy find you have started supporting WinDivert! Now we can inject packet on windows with SharpPCap!

Is there any chance to implement WinDivert.SentPacket sooner?

**Comment by kayoub5** [comment]
@BarbaTunnelCoder PR already implemented, you can give it a try by checking https://github.com/chmorgan/sharppcap/pull/142

**Comment by BarbaTunnelCoder** [comment]
I am working with it. There are two problems at the moment. I hope I can use this class without modifying the source code.

1) In WinDivertDevice.Open You have hardcodded that flag to 1, I need a property to set it to 0 so I can drop the packets.
2) There is no way to know what DstAddress.IfIdx, DstAddress.SubIfIdx should be unless I modify the source code and save them after calling ret = WinDivertNative.WinDivertRecv(Handle, new IntPtr(p), (uint)buffer.Length, out readLen, out addr);

`public void Open()
        {
            var handle = WinDivertNative.WinDivertOpen(Filter, WinDivertLayer.Network, 0, **1**);
            if (handle == IntPtr.Zero || handle == new IntPtr(-1))
            {
                ThrowLastWin32Error("Failed to open");
            }
            Handle = handle;
        }`

**Comment by chmorgan** [comment]
@kayoub5 should I wait to review the pr until you consider these requested changes?

**Comment by chmorgan** [comment]
@kayoub5 are you planning to modify the code as @BarbaTunnelCoder mentioned to add support for dropping packets and to look at approaches to expose that info above?

**Comment by chmorgan** [comment]
@BarbaTunnelCoder can you test with the master version of sharppcap and report your results and feedback? @kayoub5 has implemented your comments.

**Comment by BarbaTunnelCoder** [comment]
> @BarbaTunnelCoder can you test with the master version of sharppcap and report your results and feedback? @kayoub5 has implemented your comments.

It works on my project; 
I have call to "var divertPacket = new WinDivertPacket(ipPacket.BytesSegment) for every packet I send. I am not sure but I hope it is fast enough and doesn't put much stress on machines.

**Comment by chmorgan** [comment]
Closing this out as it looks like its fixed. @BarbaTunnelCoder feedback and PRs of course welcome!
