### ISSUE TITLE
ICaptureDevice.MacAddress is always null.

### ISSUE THREAD

**Issue by fl0kng** [chmorgan/sharppcap#161]
I am using SharpPcap 5.2.0 on latest Windows 10 with NPcap 0.9997. 
ICaptureDevice.MacAddress is always null for all my devices. It has been working before with the same Codebase but different version of SharpPcap and NPcap.

**Comment by chmorgan** [comment]
can you try the branch in this PR to see if it https://github.com/chmorgan/sharppcap/pull/160 resolves your issue? I can verify it appears to do so here on OSX but I'd like results from Windows.

**Comment by dibitkof** [comment]
Unfortunately it did not fix it for me.
Since I have un-/installed various versions of npcap and winpcap lately (and could not get it to work anymore) my machine might be messed up somehow.
Thanks for replying though.

**Comment by kayoub5** [comment]
@chmorgan For your information, `ICaptureDevice.MacAddress` will always return null for Npcap loopback device, and non Ethernet interfaces. That case is not a bug.

**Comment by dibitkof** [comment]
> @chmorgan For your information, `ICaptureDevice.MacAddress` will always return null for Npcap loopback device, and non Ethernet interfaces. That case is not a bug.

It's null for all devices.

**Comment by dibitkof** [comment]
@chmorgan seems to work now with 5.3.0 release. I think I did not reference my build of cmm_zpaul in all projects properly.
