### ISSUE TITLE
Only one device can be opened at a time.

### ISSUE THREAD

**Issue by fl0kng** [chmorgan/sharppcap#162]
When opening a second device ICaptureDevice.GetNextPacket() throws DeviceNotReady exception {"Device must be opened via Open() prior to use"}. Capturing with each device individually works though.

**Comment by chmorgan** [comment]
Can you provide a buildable failing example? What you are trying to do should be possible.

**Comment by fl0kng** [comment]
There you go, simplified example of what I am doing:
[SharpPcapEval.zip](https://github.com/chmorgan/sharppcap/files/5255529/SharpPcapEval.zip)

I kind of figured it out. I am opening and closing the adapter in short succession in my FindDevice method and then reopening it to start capturing. By slightly refactoring the code or adding a delay the error disappears.
The original exception is actually a first chance exception, but the underlying thread seems to crash, since no further packages are captured. Or the "asynchronous" Open()/Close() does not succeed at all.

Open() and Close() should be blocking calls then or (even better) awaitable.

Thanks.

**Comment by chmorgan** [comment]
Thank you for sending that over. I’ll take a look tonight.

I’m behind on my c#, suggestions on how to make them awaitable?

Chris

**Comment by fl0kng** [comment]
>I’m behind on my c#, suggestions on how to make them awaitable?

The method would have to return a System.Threading.Tasks.Task. You can look into TaskCompletionSource<T> to transform an event based pattern (or similar) into an awaitable task.

But the actual problem seems to be the underlying pcap implementation. I had a quick look at the api and I did not find anything that indicates whether a device is actually done closing and can be reopened. Just calling pcap_open/pcap_close does not do the trick obviously.

**Comment by kayoub5** [comment]
@fl0kng I use capture devices in multi threaded environment, and Open() and Close are synchronous methods.

However, the capture device is not thread safe, accessing the same device from multiple threads could result in unexpected behavior, in your particular case, you are accessing the device twice in parallel with two calls to the async function `AddDevice`.

If you need multi-threaded use of the capture device, support you could either:
* lock, so only one thread can access the same capture device at the same time
* create a capture device for each thread (creating multiple capture devices on the same physical interface is a valid use case)

**Comment by fl0kng** [comment]
Thank you for looking into it, @kayoub5.

> * create a capture device for each thread (creating multiple capture devices on the same physical interface is a valid use case)

Doing that actually solves the issue :)
So I use CaptureDeviceList.New() instead of .Instance, is this the preferred way to achieve that?

**Comment by chmorgan** [comment]
@fl0kng CaptureDeviceList.New() is the recommended approach as you would get another device handle that is distinct at the pcap layer.

I haven't had a chance to look at your example yet, I apologize, let us know if the New() approach fixes things.
