### ISSUE TITLE
There is a problem with sharppcap 4.2 upgrade 5.3

### ISSUE THREAD

**Issue by earthcoin123** [chmorgan/sharppcap#163]
I update sharppcap 4.2 to 5.3.
When compiling, it prompts that CS1501 "Extract" method does not use 1 parameter overload.
How to solve this problem,thanks. 

private void device_OnPacketArrival(object sender, CaptureEventArgs e)
		{
		Packet val = Packet.ParsePacket(e.Packet.LinkLayerType, e.Packet.Data);
		TcpPacket val2 = (TcpPacket)val.Extract((Type)(object)typeof(TcpPacket));  //  sharppcap 4.2 ,use WinPcap,normal
		if (val2 == null)
			{
				return;
			}

private void device_OnPacketArrival(object sender, CaptureEventArgs e)
		{
		Packet val = Packet.ParsePacket(e.Packet.LinkLayerType, e.Packet.Data);
		TcpPacket val2 = (TcpPacket)val.Extract((Type)(object)typeof(TcpPacket));  //sharppcap 5.3 ,use Npcap, CS1501 error
		if (val2 == null)
			{
				return;
			}

**Comment by chmorgan** [comment]
We did change the api between those versions for the better. You can find this info in the examples for sharppcap and for packetdotnet.

You'll want to use something like:

`
            var tcpPacket = packet.Extract<PacketDotNet.TcpPacket>();
            if (tcpPacket != null)
            {
                var ipPacket = (PacketDotNet.IPPacket)tcpPacket.ParentPacket;
                System.Net.IPAddress srcIp = ipPacket.SourceAddress;
                System.Net.IPAddress dstIp = ipPacket.DestinationAddress;
                int srcPort = tcpPacket.SourcePort;
                int dstPort = tcpPacket.DestinationPort;

                Console.WriteLine("{0}:{1}:{2},{3} Len={4} {5}:{6} -> {7}:{8}",
                    time.Hour, time.Minute, time.Second, time.Millisecond, len,
                    srcIp, srcPort, dstIp, dstPort);
            }
`
