### ISSUE TITLE
 `libpcap.so` can't be found

### ISSUE THREAD

**Issue by odedshimon** [chmorgan/sharppcap#167]
Hi Chris,
First, thanks for this amazing package!

There is exception that raised while using SharpPcap on Linux machines (tested on both Ubuntu 18.04 and Ubuntu 16.04).
I think that SharpPcap is looking for the file `libpcap.so` while the file could be named differently (e.g. `libpcap.so-1.2.1`).

I have managed solved the bug at that time by creating a workaround -  symbolic link between the wanted path and the real one: 
 - Find the actual: ls /usr/lib/x86_64-linux-gnu | grep libpcap
 - Create symlink: ln -s <actual> libpcap.so

**Comment by chmorgan** [comment]
Yeah this is a pain due to the mapping used with libraries. Is there a better way to do this so we can search for several different libpcap versions?

**Comment by odedshimon** [comment]
Hi Chris,
I believe it's a real pain 😄 
 
I think that trying to dynamically search for the appropriate file in "/usr/lib/x86_64-linux-gnu" directory only when `libpcap.so` is not there will solve the problem. 

That can be done as best effort, means that only when the exception is raised - search a file with that structure: 'libpcap.so-x.x.x' and use it instead `libpcap.so` (Regex pattern or a similar check?).

I assume that this mitigation will not harm the current situation and will solve the cases I have encountered (Ubuntu 18 \ 16)

**Comment by chmorgan** [comment]
Yeah it has been for a while...

Have you looked at how we do the mapping to the library via .net? Is there
a way to provide it with the wild card for the match?

**Comment by kayoub5** [comment]
@odedshimon 
Normally .NET takes care of loading the `.so` file, what's the output of `ldconfig -p | grep libpcap` ?

See also https://www.mono-project.com/docs/advanced/pinvoke/dllnotfoundexception/

**Comment by odedshimon** [comment]
@kayoub5
![image](https://user-images.githubusercontent.com/18364847/99916668-1c295a00-2d14-11eb-862a-0943c7e51642.png)

**Comment by odedshimon** [comment]
I didn't mentioned it, but I'm not using Mono, my app is .NET Core app, compiled as a single file.
But I'm pretty sure it happened also when I used Mono on previous versions of my app.

**Comment by Marschall-dev** [comment]
> 
> 
> Hi Chris,
> First, thanks for this amazing package!
> 
> There is exception that raised while using SharpPcap on Linux machines (tested on both Ubuntu 18.04 and Ubuntu 16.04).
> I think that SharpPcap is looking for the file `libpcap.so` while the file could be named differently (e.g. `libpcap.so-1.2.1`).
> 
> I have managed solved the bug at that time by creating a workaround - symbolic link between the wanted path and the real one:
> 
>     * Find the actual: ls /usr/lib/x86_64-linux-gnu | grep libpcap
> 
>     * Create symlink: ln -s  libpcap.so

I have found the same bug in Debian 10.7.0 using .NET Core.
![grafik](https://user-images.githubusercontent.com/36601278/101702270-d513c680-3a80-11eb-95da-c0a23e34edd9.png)

**Comment by kayoub5** [comment]
@chmorgan I checked ubuntu package files, and `libpcap.so` is a valid library file if you install `libpcap-dev` instead of just installing `libpcap`
See https://packages.ubuntu.com/xenial/amd64/libpcap0.8-dev/filelist and https://packages.ubuntu.com/xenial/amd64/libpcap0.8/filelist

I know it's not optimal, but I believe it's cleaner than manually symlinking files

**Comment by chmorgan** [comment]
@kayoub5 agreed. And when we put in place the library searching we should be able to avoid both cases, both the libpcap-dev package AND manual symlinking.
