### ISSUE TITLE
kernel_buffer_size parameter usage

### ISSUE THREAD

**Issue by quenzim** [chmorgan/sharppcap#172]
Have you ever used kernel_buffer_size on ICaptureDevice.Open method , how can I use that ?

**Comment by kayoub5** [comment]
It's basically how much buffer you allocate to the device. 

It protects against packet loss caused by temporary sudden increase in bandwidth.

**Comment by cemoil** [comment]
Hello,

I am trying to use it in different sizes but I got the following error for all sizes. Here are some values I have tried; 2, 65535, 2 * 1024 * 1024, 50 * 1024 * 1024 bytes. What could be the cause of the problem? Could it be related to the network card?

System.InvalidOperationException: pcap_setbuff() failed

**Comment by chmorgan** [comment]
@quenzim @cemoil what library are you using with sharppcap? libpcap, npcap, winpcap?

**Comment by chmorgan** [comment]
Closed due to lack of response. Please reopen if still an issue.
