### ISSUE TITLE
SharpPcap problem detecting ipv4 on autoconfigured interfaces

### ISSUE THREAD

**Issue by lneri-onit** [chmorgan/sharppcap#176]
Good morning,
I'm using SharpPcap to list all the network interfaces on my pc obtain their ips. 
My Eth interface is automatically configured with ip address 169.254.x.x, but the "CaptureDeviceList.Instance" returns a different Ipv4, which is 0.0.0.0.
I've tried to use the Refresh() method but it's not working, the ip won't update and remains at 0.0.0.0.
Is this the intended behaviour or it could change? If I'm sure that the 0.0.0.0 is "linked" with the 169.254.x.x that would be fine for me, I can fallback to that IP (0.0...) and use it.
Can you guys help me understand this problem?
Thanks in advance,
Luca.

**Comment by Fox4148** [comment]
You should check the examples. The first one.

CaptureDeviceList is a Collection of pcap devices. You need to get a device from the list.

`CaptureDeviceList deviceList= CaptureDeviceList.Instance;`
`ICaptureDevice device=  deviceList[0];`

**Comment by chmorgan** [comment]
Closing as It sounds like the above response answered the question.
