### ISSUE TITLE
Unable to open the adapter ; Permission issue

### ISSUE THREAD

**Issue by Fox4148** [chmorgan/sharppcap#183]
I am running debian buster with monodevelop buster and latest sharppcap.

I can't open my vm device in any mode.
Vm is set to allow promicious mode and is bridged to my local network.

The last version of sharppcap only show: "Unable to Open device"
I changed the version of sharppcap to the first one in the NuGet packages,

Now the error is: "Permission denied"

`LibPcapLiveDevice device = LibPcapLiveDeviceList.Instance[0];
            device.Open(DeviceMode.Promiscuous,10);`

> Unable to open the adapter (enp0s3). enp0s3: You don't have permission to capture on that device (socket: Operation not permitted)

Posting as a last resort, Unable to fix.

EDIT:
After further evaluation my question is now clearer: 
how do I set permission for my linux user to access network interface with my monodevelop application that is using SharpPcap?

**Comment by Fox4148** [comment]
After further evaluation my question is now clearer: 
how do I set permission for my linux user to access network interface with my monodevelop application that is using SharpPcap?

**Comment by chmorgan** [comment]
Isn't there a capture or Wireshark group you can join? Maybe this helps? https://stackoverflow.com/questions/63994958/run-libpcap-without-sudo-root

**Comment by Fox4148** [comment]
> 
> 
> Isn't there a capture or Wireshark group you can join? Maybe this helps? https://stackoverflow.com/questions/63994958/run-libpcap-without-sudo-root

I was able to run my code without the debugger by running the runtime mono in sudo for my app.
 

Even setting those capabilities to my app "After build" didn't work. I think i need to set those capabilities to the mono runtime itself. I haven't been able to succeed so far.

**Comment by Fox4148** [comment]
For anybody running into this issue, the path to mono binary on debian is
/usr/bin/mono-sgen

`sudo setcap cap_net_raw,cap_net_admin=eip /usr/bin/mono-sgen`

and now i was able to debug inside monodevelop.
