### ISSUE TITLE
PcapStatistics overflowing uint.max 

### ISSUE THREAD

**Issue by danairis** [chmorgan/sharppcap#189]
Running on Windows Server machines we are facing overflowed values in statistics.

On a 64 bit machine, ps_recv and ps_drop are 64 bit, which means they can grow to ulong.max. 
When the statistics pass uint.max, we get wrong numbers due to overflow. 

_this.ReceivedPackets = (uint)managedStat.ps_recv;
this.DroppedPackets = (uint)managedStat.ps_drop;_

How would you feel about changing the ReceivedPackets & DroppedPackets properties from uint to ulong?

**Comment by chmorgan** [comment]
Hi @danairis. How do you know that ps_recv and ps_drop are 64bit on 64bit machines? Everything I've seen so far indicates these fields are u_int (which should map to 32bits on windows 64bit), https://github.com/the-tcpdump-group/libpcap/blob/aa818d3fe5add3f69b87671fc17f8eeb09f10139/pcap/pcap.h.

**Comment by danairis** [comment]
Hi @chmorgan 
Thanks for the provided reference.
We mistakenly looked at the code part for Unix which uses IntPtr instead of uint.
The reference you provided showed the problem is coming from libpcap which also uses u_int,
And we know for a fact that after capturing for a day on high traffic machines the uint overflows unchecked.
We will have to handle this in our code to check when it happens and adjust.
Thanks for your help, we can close this issue now.

**Comment by chmorgan** [comment]
It might be worth an ask via a GitHub issue on libpcap to see about
extending these to 64bit values.

**Comment by chmorgan** [comment]
@danairis closing this one out as it looks like this is limited by the capture library itself. We'd be happy to change the types if they do expand to 64bits which would make a ton of sense as every system these days is 64bit.

**Comment by danairis** [comment]
@chmorgan It makes sense. Until then, we will have to adapt to this limitation. We appreciate your responsiveness and support.
