### ISSUE TITLE
Cannot ARP resolve the local computer

### ISSUE THREAD

**Issue by tom-2015** [chmorgan/sharppcap#19]
I've tried the ARP resolve example and it works for resolving the IP of other devices on the network. It fails to resolve the IP of the computer that's running the code/program.
Windows 10 64bit, using npcap 0.82.
Any ideas?

**Comment by chmorgan** [comment]
Does it also fail on other versions of windows?

**Comment by tom-2015** [comment]
Don't know, only tested on Windows 10

**Comment by chmorgan** [comment]
Sounds like it could be OS related though if it works on other computers. Why not use normal network interface APIs to find the local network interface IPs?

**Comment by chmorgan** [comment]
Without any additional information why this might occur or how to resolve it I don't see a path forward here. It may be something fundamental about the network stack on Windows. Please reopen if you have some ideas how to proceed as it isn't Sharppcap that is filtering these packets out.
