### ISSUE TITLE
Do not work on Linux/Ubuntu

### ISSUE THREAD

**Issue by qingyuanxingsi** [chmorgan/sharppcap#2]
When I build the project and use it in Ubuntu 14.04/Mono,I get the following mistake:

**Error CS0246: The type or namespace name `LivePcapDevice' could not be found. Are you missing an assembly reference? (CS0246)**

Would you be so kind as to tell me how to fix this error?Or am I doing it in a wrong way,if so,please point out.

**Comment by chmorgan** [comment]
Sounds like you aren't importing the assembly into your project. This is something that you have to do when using any external assembly with c#/vb.net.
