### ISSUE TITLE
OnCaptureStopped called with Status = CompletedWithoutError

### ISSUE THREAD

**Issue by pedrolcl** [chmorgan/sharppcap#22]
Hi,

When capturing asynchronous events, the status param of OnCaptureStopped() sometimes contains CaptureStoppedEventStatus.CompletedWithoutError when Device.LastError contains "read error: PacketReceivePacket failed". Please find attached a patch to fix the status value in this case.

Regards,
Pedro

[sharppcap_patch.diff.txt](https://github.com/chmorgan/sharppcap/files/979259/sharppcap_patch.diff.txt)

**Comment by chmorgan** [comment]
Looks like a solid fix. I've applied the change, by hand.
