### ISSUE TITLE
wpcap dll not found

### ISSUE THREAD

**Issue by SimonRPI** [chmorgan/sharppcap#23]
I tried the examples at first on Windows after installing WinPcap and it worked fine.
After that I installed libpcap-dev on my RaspberryPi3 and it didnt work.

It throws in LibPcapLiveDeviceList.cs a dllNotFoundException for wpcap.

Any reasons for that?

**Comment by chmorgan** [comment]
You'll want to copy SharpPcap.dll.config into that folder, that's what defines the mapping from wpcap to libpcap.so. It isn't elegant for sure. I'm not sure that we can always copy the files into the output directory without affecting windows...

**Comment by termhn** [comment]
Copy SharpPcap.dll.config into the LibPcap folder?

**Comment by SimonRPI** [comment]
Yes, it worked. Thank you both.
Problem solved
