### ISSUE TITLE
"LinkLayer of Raw is not implemented" Exception

### ISSUE THREAD

**Issue by ThojoyBettan** [chmorgan/sharppcap#24]
Attached file can be opened using Wireshark but not with SharpPCap. 
Exception is thrown as in subject line. Is there any workaround?

Thanks.

**Comment by chmorgan** [comment]
Hello.

What version of sharppcap are you using? The latest release should support the raw link layer.

**Comment by ThojoyBettan** [comment]
Hello

I was trying with 4.2. Its working with 4.3. Thank you very much.
