### ISSUE TITLE
How to test these methods?

### ISSUE THREAD

**Issue by chmorgan** [chmorgan/sharppcap#240]
@kayoub5 these methods are private and untested at the moment, should they be public so they can be called and tested?

https://codecov.io/gh/chmorgan/sharppcap/src/master/SharpPcap/LibPcap/CaptureFileWriterDevice.cs

**Comment by chmorgan** [comment]
And thats lines 207 and 212 since the codecov link after clicking on the line numbers doesn't update with the line number, the two Inject methods.

**Comment by kayoub5** [comment]
They are [Explicit Interface Implementation](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/interfaces/explicit-interface-implementation)
you simply need to use the interface type to use them.
```
IInjectionDevice device = new CaptureFileWriterDevice(...);
device.SendPacket(...)
```

**Comment by chmorgan** [comment]
Done and merged.
