### ISSUE TITLE
Do we need these StatisticsDevice methods?

### ISSUE THREAD

**Issue by chmorgan** [chmorgan/sharppcap#243]
These methods of StatisticsDevice are not currently tested as indicated by codecov.

        public void Capture()
        {
            PrepareCapture();
            LiveDevice.Capture();
        }

        public void Capture(int packetCount)
        {
            PrepareCapture();
            LiveDevice.Capture(packetCount);
        }

Do we need these methods? Should we fold the Capture() ones into a single with a default count of 0 or something, or do that with LiveDevice.Capture() first so we can use it here?

Or do we add tests for these in the StatisticsDeviceTest?

**Comment by kayoub5** [comment]
those methods only exist to provide a similar api surface between libpcap devices and statistics devices, nothing more.
