### ISSUE TITLE
nuget package

### ISSUE THREAD

**Issue by VerusMaya** [chmorgan/sharppcap#25]
Could you please publish nuget packages for the new SharpPcap and Packet.Net releases?

Thank you!

**Comment by chmorgan** [comment]
Hello.

I'd like to. I'm working on it but someone is using the SharpPcap and PacketDotNet IDs on Nuget. I've reached out to the guy using those ID values but the policy is to wait 30 days before they take any action and it hasn't been 30 days yet, it will be in another week or so and I'll reach back out to the nuget guys about it.

Chris

**Comment by VerusMaya** [comment]
Oh wow, yeah I did not even realize that you are not the owner for those.

**Comment by stricq** [comment]
Any update on the Nuget packages?

**Comment by chmorgan** [comment]
@stricq yep, I should have access to the IDs on nuget shortly and I'll look at pushing new libraries out in the next few days.

**Comment by chmorgan** [comment]
@stricq and already hit a roadblock. Nuget doesn't support building packages under Linux and I lack a Windows license to build a VM (assuming the free .net tools would be sufficient at that point). Not sure what to do next. Thoughts?

**Comment by chmorgan** [comment]
@stricq, @VerusMaya nuget packages push. Feedback welcome on whether the contents is correct, works etc. I can't easily test pushing here, I'm using appveyor for that.
