### ISSUE TITLE
winpcap dll not found

### ISSUE THREAD

**Issue by JohnnyZhang0628** [chmorgan/sharppcap#250]
Hello,I have a question.When i run sharppcap in windows,i must intall npcap?I found if i not install npcap, it will get an error "winpcap dll not found"

**Comment by kayoub5** [comment]
Yes, you need npcap on windows

**Comment by JohnnyZhang0628** [comment]
@kayoub5 thanks.There is it have other way  solve  to the question?

**Comment by kayoub5** [comment]
you could use Windivert (no installation required) or WinPcap.

**Comment by JohnnyZhang0628** [comment]
@kayoub5 thanks your reply.
