### ISSUE TITLE
Allow setting monitor mode

### ISSUE THREAD

**Issue by SapientGuardian** [chmorgan/sharppcap#27]
Hello,

It would be great if SharpPcap allowed you to set monitor mode. 

The [pcap_set_rfmon](http://www.tcpdump.org/manpages/pcap_set_rfmon.3pcap.html) api must be applied after an adapter is created, but before it is activated. Unfortunately, SharpPcap uses the `pcap_open_live` api that performs `pcap_create` and `pcap_activate` in one shot, which means there's no opportunity to call `pcap_set_rfmon`.

I see two obvious ways to solve this. The least invasive in terms of API would be to add another `Open` overload which doesn't use `pcap_open_live` and allows setting of monitor mode, something like this:
```C#
public override void Open(DeviceMode mode, int read_timeout, Boolean monitor_mode)
        {
            if ( !Opened )
            {
                StringBuilder errbuf = new StringBuilder( Pcap.PCAP_ERRBUF_SIZE ); //will hold errors

                // set the StopCaptureTimeout value to twice the read timeout to ensure that
                // we wait long enough before considering the capture thread to be stuck when stopping
                // a background capture via StopCapture()
                //
                // NOTE: Doesn't affect Mono if unix poll is available, doesn't affect Linux because
                //       Linux devices have no timeout, they always block. Only affects Windows devices.
                StopCaptureTimeout = new TimeSpan(0, 0, 0, 0, read_timeout * 2);

                PcapHandle = LibPcapSafeNativeMethods.pcap_create(
                    Name, // name of the device
                    errbuf); // error buffer                

                if ( PcapHandle == IntPtr.Zero)
                {
                    string err = "Unable to open the adapter ("+Name+"). "+errbuf.ToString();
                    throw new PcapException( err );
                }

                LibPcapSafeNativeMethods.pcap_set_snaplen(PcapHandle, Pcap.MAX_PACKET_SIZE);
                LibPcapSafeNativeMethods.pcap_set_rfmon(PcapHandle, monitor_mode ? 1 : 0);
                LibPcapSafeNativeMethods.pcap_set_promisc(PcapHandle, mode == DeviceMode.Promiscuous ? 1 : 0);
                LibPcapSafeNativeMethods.pcap_set_timeout(PcapHandle, read_timeout);

                var activationResult = LibPcapSafeNativeMethods.pcap_activate(PcapHandle);
                if (activationResult < 0)
                {
                    string err = "Unable to activate the adapter (" + Name + "). Return code: " + activationResult.ToString();
                    throw new PcapException(err);
                }
                PcapHandle = PcapHandle;
            }
        }
```
The second, more invasive way, would be to expose API to do the `pcap_create`, all of the `pcap_set_` methods, and `pcap_activate`, but that seems way too leaky to me.

Is this something you'd be interested in supporting? I'm happy to submit a PR if we can agree on an API.

**Comment by chmorgan** [comment]
What would you be able to accomplish if you were able to put the interface into monitor mode? I'm not familiar with its usage. Knowing more about that would help to know where it might go in the API.

**Comment by SapientGuardian** [comment]
When used against Npcap, this allows you to capture 802.11 packets under Windows. And I suppose if you were to use SharpPcap on another platform that supported it natively, then it would help you there too.

If you install Npcap and you use SharpPcap (or anything else for that matter) to capture from a wifi adapter that isn't associated with a network, you'll get a link type of Ethernet and you won't see any packets. But if you enable monitor mode, the link type will be Ieee80211_Radio, and you'll be able to see packets.

**Comment by chmorgan** [comment]
Is it possible to pcap_open_live functionality with these separate calls that would be ideal and would let us have a single fully featured Open() call that the other versions can call through to.

I prefer enums vs. booleans, so the code can be understood by its usage vs. having to look up what that boolean decodes to. so enum MonitorMode { active, inactive} as the last parameter.

If you could accomplish both of those and the unit tests pass then I'd like to see a PR.

**Comment by SapientGuardian** [comment]
PR submitted. I did my best to match your code style, but let me know if you'd like something done differently - or feel free to make changes directly, I've enabled maintainer edits. Thanks!

**Comment by chmorgan** [comment]
Pull request merged, closing this out, thanks again for the contribution. More are welcome!
