### ISSUE TITLE
SharpPcap not working on Raspberry PI 4 (Return code: -8)

### ISSUE THREAD

**Issue by synpse** [chmorgan/sharppcap#274]
![image](https://user-images.githubusercontent.com/33324663/115010260-1b50ba80-9ea5-11eb-9608-78240ced9fdb.png)

I have already updated libpcap on the PI but this keeps appearing. No idea what that error code is.

I'm currently using DeviceMode.Promiscuous, although I have tried with DeviceMode.Normal. Also current timeout is 2500 but I've tried with 1000 and even with 10000, so I've got no clue what to problem could be.

**Comment by kayoub5** [comment]
are you running the application as root?

**Comment by synpse** [comment]
> are you running the application as root?

I was not, it does work with sudo. I'm that stupid. Thanks!
