### ISSUE TITLE
PosixTimeval and OnPacketArrival on multiple event inconsistent?

### ISSUE THREAD

**Issue by charleslales** [chmorgan/sharppcap#277]
Hi,

Sniffing udp packet between 2 endpoints, one emtting each 200ms, the other answering directly, I get a behavior I don't understand...
It is WinForms app using NLog and SharpPcap (over Npcap) under Win10.
Debug as release generate same result.
PosixTimeval are all consistent, but OnPacketArrival events seem to be packed with periodically 1s gap.

` private void Device_OnPacketArrival(object o, CaptureEventArgs e)
{
    var time = e.Packet.Timeval.Date.ToLocalTime();
    var len = e.Packet.Data.Length;
    Logger.WithProperty("capture", "on").Info($"{DateTime.Now:yyyy-MM-dd HH:mm:ss.fff} packet received {time:yyyy-MM-dd HH:mm:ss.fff} Len={len}");
}`

<DateTime.Now> .. <Packet.Timeval> ..
18:24:36.793 packet received 18:24:36.389 Len=78 -> one msg
18:24:36.803 packet received 18:24:36.406 Len=40 -> answer
18:24:36.804 packet received 18:24:36.597 Len=78 
18:24:36.805 packet received 18:24:36.598 Len=40 
18:24:37.834 packet received 18:24:36.811 Len=78 -> here, 1s jump on DateTime.Now
18:24:37.836 packet received 18:24:36.812 Len=40 
18:24:37.836 packet received 18:24:37.012 Len=78 
18:24:37.837 packet received 18:24:37.013 Len=40 
18:24:37.839 packet received 18:24:37.213 Len=78 
18:24:37.840 packet received 18:24:37.214 Len=40 
18:24:37.842 packet received 18:24:37.414 Len=78 
18:24:37.843 packet received 18:24:37.415 Len=40 
18:24:37.844 packet received 18:24:37.615 Len=78 
18:24:37.845 packet received 18:24:37.616 Len=40 
18:24:38.848 packet received 18:24:37.839 Len=78 -> here, 1s jump on DateTime.Now 
18:24:38.849 packet received 18:24:37.839 Len=40 
18:24:38.851 packet received 18:24:38.059 Len=78 
18:24:38.852 packet received 18:24:38.061 Len=40 
18:24:38.853 packet received 18:24:38.295 Len=78 
18:24:38.855 packet received 18:24:38.297 Len=40 
18:24:38.856 packet received 18:24:38.508 Len=78 
18:24:38.857 packet received 18:24:38.510 Len=40 
18:24:38.858 packet received 18:24:38.708 Len=78 
18:24:38.860 packet received 18:24:38.710 Len=40 
18:24:39.862 packet received 18:24:38.910 Len=78 -> here, 1s jump on DateTime.Now
18:24:39.864 packet received 18:24:38.912 Len=40 

Checking SharpPcap code source, StartCapture starts one dedicated CaptureThread with infinite loop (until cancellation requestd) with LibPcapSafeNativeMethods.pcap_dispatch supposely firing the event OnPacketArrival..

But I don't see any pause or smthg equiv.

Thanks in advance for explanation and idea ;-)
Kind regards,
Charles

**Comment by kayoub5** [comment]
the one second is the read timeout default value, you could decrease it, or set devices in immediate mode to bypass it

**Comment by kayoub5** [comment]
You set `MinToCopy` to 0

See https://www.tcpdump.org/manpages/pcap_set_immediate_mode.3pcap.html

**Comment by charleslales** [comment]
Thanks!
Would it be possible to highlight these options in documentation maybe?

**Comment by chmorgan** [comment]
@charleslales would you have a recommendation on where we might note that?

**Comment by charleslales** [comment]
Sure, simply in documentation > features > capturing packet, little mention that Open can take some params to make it RT ;-)

**Comment by chmorgan** [comment]
@charleslales do you have a url to that location? We don't have a documentation folder in the repo so I'm not sure where you might mean.

**Comment by chmorgan** [comment]
Closing due to lack of response.
