### ISSUE TITLE
I'm only seeing the loopback adapter

### ISSUE THREAD

**Issue by MikeYeager** [chmorgan/sharppcap#286]
```
var devices = LibPcapLiveDeviceList.Instance;
int i = 0;
foreach (var dev in devices)
{
    Console.WriteLine("{0}) {1} {2}", i, dev.Name, dev.Description);
    i++;
}
```
I am trying this on Windows 10 with .NET 6 Preview 4. When I run the above code, all I see is the loopback adapter. Any idea why this might be?

**Comment by kayoub5** [comment]
What adapters do you see in wireshark?

**Comment by MikeYeager** [comment]
@kayoub5 same thing in WireShark. Does it not list WiFi adapters? Or might it have something to do with HyperV virtual switches?

**Comment by MikeYeager** [comment]
@kayoub5 There was an update to WireShark, so I installed it. After installing, I see all the adapters, so I re-ran the code and now everything shows up. Odd, but re-installing WireShark fixed the problem. Thanks for the push in the right direction.
