### ISSUE TITLE
SharpPcap.PcapException: Unable to activate the adapter: Return code: -4

### ISSUE THREAD

**Issue by kpolicar** [chmorgan/sharppcap#291]
Issue when attempting to open a remote device through winpcap, the server (rpcap) running on a different machine on the local network. The firewall of the server is turned off.

Exception:
```csharp
SharpPcap.PcapException: Unable to activate the adapter (rpcap://\Device\NPF_{F4F5CA25-92B2-4E19-9648-0111D6553B55}). Return code: -4
   at SharpPcap.LibPcap.LibPcapLiveDevice.Open(DeviceConfiguration configuration)
   at SharpPcap.CaptureDeviceExtensions.Open(IPcapDevice device, DeviceModes mode, Int32 read_timeout)
```

From what I could find, return code -4 is described as:
**the operation can't be performed on already activated captures**
Source: https://github.com/the-tcpdump-group/libpcap/blob/master/pcap/pcap.h

Why does **PcapInterface.GetAllPcapInterfaces** not return the interfaces on the server? Why is it returning the interfaces from my local machine?

My code:
```csharp
var ipAddress = System.Net.IPAddress.Parse("192.168.0.14");
var port = 2002;

var credentials = new RemoteAuthentication(AuthenticationTypes.Password, "pcap", "password");
var remoteInterfaces = PcapInterface.GetAllPcapInterfaces(new IPEndPoint(ipAddress, port), credentials);

using var device = new LibPcapLiveDevice(remoteInterfaces[0]);
device.OnPacketArrival += PacketHandler;
device.Open(DeviceModes.Promiscuous);
device.StartCapture();
```

What I get when using Wireshark (it finds the correct, remote devices) and can capture them correctly:
![aaaa](https://user-images.githubusercontent.com/9630422/124488911-b2485700-ddb0-11eb-903f-9aadbe330923.png)

I was following the example provided:
https://github.com/chmorgan/sharppcap/blob/master/Examples/NpcapRemoteCapture/Program.cs
but I could not get it working. Any help is appreciated, or if you could let me know that this is not supported.

Update:
After removing password authentication -> switching to null authentication, and changing the method argument to:
```csharp
var remoteInterfaces = PcapInterface.GetAllPcapInterfaces("rpcap://192.168.0.14:2002/", null);
```
The backslash at the end of the IP endpoint is important.
I can now successfully list the correct remote interfaces.

Now I get a new issue: 
```csharp
SharpPcap.PcapException: Unable to activate the adapter (rpcap://192.168.0.14:2002/\Device\NPF_{084A8D4B-2131-4CDB-84F3-A617A480FAD0}). Return code: -5
   at SharpPcap.LibPcap.LibPcapLiveDevice.Open(DeviceConfiguration configuration)
   at SharpPcap.CaptureDeviceExtensions.Open(IPcapDevice device, DeviceModes mode, Int32 read_timeout)
```

**Comment by kayoub5** [comment]
@kpolicar What version of Libpcap/WinPcap/Npcap do you have installed in the server and client?

**Comment by kpolicar** [comment]
> @kpolicar What version of Libpcap/WinPcap/Npcap do you have installed in the server and client?

Client: npcap 1.50
Server: Winpcap 4.1.3

**Comment by kayoub5** [comment]
the unit tests we have are for winpcap and libpcap, last time I checked npcap support for rpcap was broken.
could you test with both client and server winpcap?

**Comment by kpolicar** [comment]
> the unit tests we have are for winpcap and libpcap, last time I checked npcap support for rpcap was broken.
> could you test with both client and server winpcap?

It appears to work now that I have winpcap on both computers. Thanks :)
