### ISSUE TITLE
Linux - Unable to Activate Adaptor (vethxxx). Return Code: -8

### ISSUE THREAD

**Issue by bpanhale** [chmorgan/sharppcap#297]
Hello Team,

I am facing below issue on linux device. I am using Ubuntu 18.04 LTS OS to run this solution.
On windows system it is working properly but on Linux is throws some exception.

Please let me know if you need more details of device.
![image](https://user-images.githubusercontent.com/41563693/129524667-8f4ce98c-f086-4a5d-acfc-810497a7c6ee.png)

**Comment by kayoub5** [comment]
run the application as root with sudo

**Comment by bpanhale** [comment]
Hello @kayoub5,

Thank you. Now it is working on Linux host machine.
Actually I was deploying IoT Edge module with Linux containers. I am trying to access Host network inside the container. I have setup the deployment template file as mentioned here - https://github.com/Azure/iot-edge-v1/issues/517#issuecomment-407453239

But still having the issue as given in the below screenshot. Is there anything that I am missing here?
![image](https://user-images.githubusercontent.com/41563693/129886592-beea8808-c247-4a65-bba5-8eb2f69c3567.png)
 
Thank you.

**Comment by kayoub5** [comment]
The error you see comes from libpcap itself, sharppcap simply forwards it in the form of an exception.

I believe containers need to run privileged, or have some kind of pci express passthrough in order to have access to the adapter through libpcap.

**Comment by bpanhale** [comment]
Hi @kayoub5,

Thank you for your suggestions. I am able to run application without any exception but packet capture is stopped immediately. Is there any way to check logs to check what is happening in the backend. Please refer below screenshot that I can see on the console.

![image](https://user-images.githubusercontent.com/41563693/130588008-80c8ce92-af41-4f9a-9026-70ea93550884.png)

**Comment by kayoub5** [comment]
check the status reported in the capture stop event, it usually explains why the capture stopped

**Comment by kayoub5** [comment]
@bpanhale do you receive traffic if you use the `any` interface ?

**Comment by bpanhale** [comment]
Hello @kayoub5,

Yes, I am able to receive traffic on 1st and 2nd interface by adding some delay between start and stop. Interactive console app was not supported by docker container and that is why it was stopped automatically without waiting for user input.

Thank you for your time.
