### ISSUE TITLE
Update Readme

### ISSUE THREAD

**Issue by evanplaice** [chmorgan/sharppcap#3]
- [ ] make the reference to SourceForge a link
- [ ] add a reference to Packet.Net

BTW, I'm really happy to see this project still alive and transitioning to GitHub Chris. Let me know if you need any help navigating the ins/outs of GH.

**Comment by chmorgan** [comment]
Hi Evan.

Thanks for the offer. github is much nicer than sourceforge, after they had
an outage and were inserting adware in their downloads I just decided I had
enough and moved things.

Are you still using the software? I've been looking for someone to take
over maintainer ship as I haven't been using or improving it in a while.

Chris

**Comment by evanplaice** [comment]
@chmorgan Honestly, I haven't done any C# development for a while. This might give me an excuse to start again. I'll let you know first thing if I do.

Worst comes to worst, you could let it coast for a while.
