### ISSUE TITLE
Non ASCII chars on path \ file name causing exception

### ISSUE THREAD

**Issue by odedshimon** [chmorgan/sharppcap#300]
Hi! 

I came across this exception when trying to read a file that contains non ASCII chars at his name:  
**"Unable to open offline adapter: <THE-FILE-PATH>: Invalid argument"**
The non ASCII chars are shown as question marks (picture attached) even though the file exists (the original file name is: "Non ASCII file name - (אבג).pcap"). 
![image](https://user-images.githubusercontent.com/18364847/130334080-491520be-5bd5-44b0-bedc-3a68c7a5df98.png)

Thank you for the efforts invested in the development of this package!

 Oded.

**Comment by kayoub5** [comment]
Solution would be to set libpcap to utf-8 mode using `pcap_init`

**Comment by chmorgan** [comment]
@kayoub5 should we be doing that by default? There was another user with a similar issue, I think Chinese locale. I don't see us calling pcap_init() anywhere at the moment.

**Comment by kayoub5** [comment]
> @kayoub5 should we be doing that by default? There was another user with a similar issue, I think Chinese locale. I don't see us calling pcap_init() anywhere at the moment.

I believe so, this ticket is easier to reproduce compared to #87
Please note that the call to pcap_init may fail old libpcap installations, since the method was added rather recently.

**Comment by chmorgan** [comment]
We don't call pcap_wsockinit either. This looks like new behavior, never heard that we needed to make such calls in the past. https://man7.org/linux/man-pages/man3/pcap_init.3pcap.html

**Comment by kayoub5** [comment]
@odedshimon could you try #303 and see if it fixes the problem for you, string encoding is a bit tricky and depends a lot on the framework/os being used

**Comment by odedshimon** [comment]
Sure.
I have tested it: cloned the repo, create an updated nuget and installed it (Windows 10, Net Core 3.1.4).

Seems that the file is still not recognized (appears as "????" although the string is "אבגדה"): 
![image](https://user-images.githubusercontent.com/18364847/131544122-52e5b2c7-6628-4859-8fcf-f0098de3c4c6.png)
![image](https://user-images.githubusercontent.com/18364847/131544199-73e96e88-d605-4991-944f-561770b055b0.png)

I have also tried the example project ("ReadingCaptureFile"), still same exception:
![image](https://user-images.githubusercontent.com/18364847/131545307-070968fa-6c80-4d00-9759-ea2dde0c603e.png)

I have uploaded an example file (just change the extension to "pcap")
[אבגדה.txt](https://github.com/chmorgan/sharppcap/files/7085588/default.txt)

**Comment by kayoub5** [comment]
@odedshimon What path does `ConfigureStringEncoding` take during initialization?
* What version of Npcap/WinPcap do you have? What does `Pcap.Version` return?
* What's your system encoding?
  - return value of `GetACP()`
  - output of `chcp` command

**Comment by kayoub5** [comment]
@odedshimon screenshot indicates you are in master branch, encoding support is still in `feature/pcap_encoding` branch

**Comment by odedshimon** [comment]
Sorry, I thought it was merged 😃 
1. Did all the above checks again after checking out this branch - no change.
2. Pcap.Version - **"Npcap version 1.50, based on libpcap version 1.10.1-PRE-GIT"**
3. ConfigureStringEncoding - I'm not sure what to check, feel free to guide me.
4. Npcap version - **1.50**
5. GetACP(), I used python to call winapi - **1252** (see attached photo)
6. chcp result - **Active code page: 437**

![image](https://user-images.githubusercontent.com/18364847/131558653-cde1c1fa-8047-4fab-a46e-ac9fd070ad98.png)

![image](https://user-images.githubusercontent.com/18364847/131558774-522886f4-b252-45f2-a72d-d2e696ddd096.png)

**Comment by kayoub5** [comment]
This indicates that the file name may have not been passed correctly to the application from the command line
![image](https://user-images.githubusercontent.com/1814900/131561522-1cb89431-ad6e-467a-8b99-2333f25de0fa.png)
The code for this line is
```
Console.WriteLine("opening '{0}'", capFile);
```
Meaning that the file name encoding may have been screwed up even before it arrived to the `CaptureFileReaderDevice`

> ConfigureStringEncoding - I'm not sure what to check, feel free to guide me.

There are 4 return statements, which one got executed, `return Encoding.UTF8;` `return Encoding.GetEncoding((int)GetACP());` or `return Encoding.ASCII`

**Comment by odedshimon** [comment]
I have verified that the path is passed properly and it seems to work:
![image](https://user-images.githubusercontent.com/18364847/131700291-f49c9e6a-9e66-41bd-b658-9eac9f0f2753.png)
Well done.
