### ISSUE TITLE
Intercept https request/response

### ISSUE THREAD

**Issue by chiptus** [chmorgan/sharppcap#31]
Wireshark and other similar services allow decrypting of https responses by installing a certificate on the browser. Is there a way to do it with SharpPCap?

**Comment by chmorgan** [comment]
That would be a cool feature. I have some http following code that I've been meaning to dual license so I can release it under gpl for non commercial use but have been hard at work on some other things. This wouldn't get you all the way there, you'd need some way to take apart the ssl communication. No idea how Wireshark does that....

**Comment by chiptus** [comment]
I'm using burp and mitmproxy, and they let you install a certificate on the browser and then uses it to decrpyt the responses.

What I think you should have is let the user self generate his own certificate, and add it as a configuration option to your service. Sounds possible?

**Comment by chmorgan** [comment]
That's a good question. I'm sure its possible given that others do it and the source is available.

**Comment by chmorgan** [comment]
Closing this out. It would be great to have this kind of stuff rolled into sharppcap or a compatible library. I'm working to push out some enhanced functionality for PacketDotNet that might help open the door for others to build upon.

**Comment by bluelucas** [comment]
Hey, I know this is quite an old issue but I was wondering if any progress has been made towards allowing a user to specify a certificate?
