### ISSUE TITLE
SharpPcap.LibPcap.LibPcapLiveDevice.Open ignores flags in SharpPcap.DeviceConfiguration.Mode 

### ISSUE THREAD

**Issue by gs-rs-21** [chmorgan/sharppcap#314]
I'm updating a C# application from SharpPcap 4.0.0 to 6.00.
The applications with 4.0.0 opens the capture device with these flags set:
`_livePcapDevice.Open(OpenFlags.MaxResponsiveness|OpenFlags.NoCaptureLocal|OpenFlags.NoCaptureRemote, 1000);`

The applications with 6.0.0 opens the capture device with these flags set:
`_livePcapDevice.Open(DeviceModes.MaxResponsiveness|DeviceModes.NoCaptureLocal|DeviceModes.NoCaptureRemote, 1000);`

Later the application captures and sends packets. With 4.0.0 the sent packets are not captured, as intended by setting the flags. **But with 6.0.0 the sent packets are captured. The flags are ignored!**

In the debugger I can see that in `SharpPcap.LibPcap.LibPcapLiveDevice.Open()` runs through the path with `LibPcapSafeNativeMethods.pcap_create()`.
In this case it needs to call LibPcapSafeNativeMethods.pcap_open(), were the mode flags are applied.

**Comment by kayoub5** [comment]
@gs-rs-21 could you open a PR with the proposed change?
