### ISSUE TITLE
Missing methods

### ISSUE THREAD

**Issue by JumpingScript** [chmorgan/sharppcap#32]
So, I want to use sharppcap in a school project and write a packet sniffer.
I recently came across two missing method declarations, which are used by @chmorgan  in this tutorial:
https://www.codeproject.com/Articles/12458/SharpPcap-A-Packet-Capture-Framework-for-NET

These are the RawInput.Extract() and the tcpPacket.SourceAdress() method.
For me, they don't show up, nor are they seem to be valid. I get a generic "Missing method" error in vs 2017 with .Net framework 4.5.1.
Hoping to find some help here.
Best wishes,
Script

**Comment by chmorgan** [comment]
Hi Script.

Can you be more specific about what methods are missing? It’s tough to
debug for me as I lack a Windows license to set up a vm but we can likely
figure it out from your info!

Chris

**Comment by JumpingScript** [comment]
Hello Chris,

**Comment by JumpingScript** [comment]
Hi Chris.

The first error I do encounter is at calling
`var tcp = (TcpPacket)e.Packet.Extract(typeof(TcpPacket));`

RawCapture seems to not contain the method Extract(). (Contrary to the aforementioned tutorial)

The second error I encounter is at calling

`tcp.SourceAdress()`
TcpPacket (in PacketDotNet namespace) does not contain the method/member SourceAdress. 

Hope this was more specific.

Script

**Comment by chmorgan** [comment]
Hmm.

The PacketNet tests do work, you can find them here:

https://github.com/chmorgan/packetnet/blob/master/Test/PacketType/TcpPacketTest.cs

So it may be that the tutorial is out of date or some library is missing
but you should get other errors in that case. Are you using the latest 4.x
SharpPcap and the packet net that it came with?

There are also examples in the source distribution of SharpPcap and packet
net,
https://github.com/chmorgan/packetnet/tree/master/Examples
https://github.com/chmorgan/sharppcap/tree/master/Examples


Chris

**Comment by JumpingScript** [comment]
Hi Chris.

I use SharppCap v4.4.0 and PacketDotNet v0.16.0.
I'll look at the examples you post, most likely the tutorial at codeproject is outdated.

**Comment by JumpingScript** [comment]
Hello again, 

just a final post. The tutorial on codeproject was indeed outdated. Thanks in advance for your help, now, I am finally able to continue with my project.
Have a good day!

Script
