### ISSUE TITLE
WinDivertDevice silently drops packets on send

### ISSUE THREAD

**Issue by FlashPlayer13** [chmorgan/sharppcap#339]
Hi. I am using 6.1 version. Windows 10.
My simple code to capture packets and send them further is:

```
private static void Main()
{
    var winDivertDevice = new WinDivertDevice();
    winDivertDevice.Flags = 0;
    winDivertDevice.OnPacketArrival += (sender, capture) =>
                                       {
                                           var rawCapture = capture.GetPacket();
                                           var packet = Packet.ParsePacket(rawCapture.LinkLayerType, rawCapture.Data);
                                           winDivertDevice.SendPacket(packet);
                                       };
    winDivertDevice.Open();
    winDivertDevice.StartCapture();

    while (true)
        Console.ReadKey();
}
```
But it doesn't work. Packets just drop somewhere. What i am doing wrong?

Visual Studio runs with admin rights (no exception about it), all three needed libs are lying in app directory.

**Comment by kayoub5** [comment]
* What do you mean by "packet dissapear"?
* About original capture.Header - what do you mean? => `winDivertDevice.SendPacket(capture.Data, capture.Header);` instead of `winDivertDevice.SendPacket(rawCapture);`
