### ISSUE TITLE
.NET Core?

### ISSUE THREAD

**Issue by fastrocket** [chmorgan/sharppcap#39]
My ASP.NET Core 2 solution blows up when I try to add this nuget. I know that it supports Mono, but are there any plans to support .NET Core?

**Comment by chmorgan** [comment]
Hi @fastrocket. Yep that's the plan. The difficulty is that I'd like to maintain full compatibility across windows, Mac, and linux and the linux side tools haven't caught up with the latest .net versions. It looks like they may be close though, http://apebox.org/wordpress/

Once I can build again on Mac and linux with .net core there will be updated releases.

**Comment by chmorgan** [comment]
Hello.

I've moved sharppcap to .net standard 2.0 so you should be able to use it with .net core. 4.5.0 has been published on nuget although it looks like only debug builds are being published. Not sure how to fix that.

Let me know if you have trouble with .net core with the latest update.
