### ISSUE TITLE
Cannot build .NET Standard project with SharpPcap.Standard 4.4.0

### ISSUE THREAD

**Issue by zamiramos** [chmorgan/sharppcap#40]
1>------ Build started: Project: FlowInterceptor, Configuration: Debug Any CPU ------
1>FlowInterceptor -> C:\Users\******\Documents\Visual Studio 2017\Projects\InjectorDemo\FlowInterceptor\bin\Debug\netstandard2.0\FlowInterceptor.dll
2>------ Build started: Project: FlowInjector, Configuration: Debug Any CPU ------
2>CSC : error CS2015: 'C:\Users\*******\.nuget\packages\sharppcap.standard\4.4.0\contentFiles\any\netstandard2.0\App.ico' is a binary file instead of a text file
2>Done building project "FlowInjector.csproj" -- FAILED.
========== Build: 1 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

Is App.ico needed to be removed from the package?

Thanks,
Amos.

**Comment by chmorgan** [comment]
Hello.

I've removed that app.ico file from the project and moved to .net standard 2.0 for sharppcap in 4.5.0 published on nuget. Let me know if you have trouble building against this version.
