### ISSUE TITLE
libpcap function pcap_findalldevs_ex is only supported in windows

### ISSUE THREAD

**Issue by zamiramos** [chmorgan/sharppcap#41]
Cannot run in Linux because some functions are only exported in windows:

> Unhandled Exception: System.EntryPointNotFoundException: Unable to find an entry point named 'pcap_findalldevs_ex' in DLL 'wpcap'.
>    at SharpPcap.WinPcap.SafeNativeMethods.pcap_findalldevs_ex(String source, IntPtr auth, IntPtr& alldevs, StringBuilder errbuf)
>    at SharpPcap.WinPcap.WinPcapDeviceList.Devices(String rpcapString, RemoteAuthentication remoteAuthentication)
>    at SharpPcap.WinPcap.WinPcapDeviceList.GetDevices()
>    at SharpPcap.WinPcap.WinPcapDeviceList.Refresh()
>    at SharpPcap.WinPcap.WinPcapDeviceList..ctor()
>    at SharpPcap.WinPcap.WinPcapDeviceList.get_Instance()

Here the full list:
[https://www.winpcap.org/docs/docs_40_2/html/group__wpcapfunc.html](https://www.winpcap.org/docs/docs_40_2/html/group__wpcapfunc.html)

In addition the native library wpcap need to be change to pcap in order to match Linux OS.

Thanks,
Amos.

**Comment by chmorgan** [comment]
Hello.

Have you included a SharpPcap.dll.config file that defines the mapping from
wpcap to libpcap? There should be an example in the source and binary
packages.

Chris

**Comment by chmorgan** [comment]
Does dotnet provide a mechanism to map dlls? The goal of course is a single
assembly that can be used across platforms.

**Comment by zamiramos** [comment]
AFAIK no.

I think that the advanced feature which winpcap gives upon libpcap should
be canceled automatically (by detecting OS) when run in Linux environment.
(inspired from
https://github.com/robertdavidgraham/isowall/blob/master/src/rawsock.c)

I want to try something buy I didn't find how you compile the source to
.Net standard. Maybe I look at the wrong branch.

Where I can find the source code of
https://www.nuget.org/packages/SharpPcap.Standard/4.4.0?

2018-04-10 13:51 GMT+03:00 Chris Morgan <notifications@github.com>:

**Comment by chmorgan** [comment]
It's a bit more complex to maintain multiple platform support but looks like it can be done via dynamic library loading. I'll probably be looking at that in the near future as dotnet has dropped support for dllmap and there isn't really another elegant way of doing it.

No idea what package that is, I'm not the publisher of it. I did just publish 4.5.0 which targets .net standard 2.0 if that's why that package is interesting to you.

**Comment by chmorgan** [comment]
Hi @zamiramos can you try the 4.6.0 release? That should address cross platform issues.
