### ISSUE TITLE
The type 'ReadOnlyCollection<>' is defined in an assembly that is not referenced

### ISSUE THREAD

**Issue by sbrl** [chmorgan/sharppcap#43]
Hello!

I've just updated from version 4.4.0 to 4.5.0, and I've got this build error:

```
<path>/Program.cs(39,39): Error CS0012: The type 'ReadOnlyCollection<>' is defined in an assembly that is not referenced. You must add a reference to assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. (CS0012) (NetworkMidiConverter)
```

**Comment by sbrl** [comment]
This is with my own application. I'm targeting .NET v4.6.1 as far as I can tell, on Linux with mono.

**Comment by chmorgan** [comment]
If I had an example I could try to reproduce. Otherwise I’d recommend adding the netstandard assembly as the message is asking for.

**Comment by sbrl** [comment]
Hrm. As far as an example goes, simply create a new console app in monodevelop, target NET v4.5.1, and add SharpPcap via nuget. If I have time I'll investigate creating such a project myself and attaching it here.

**Comment by chmorgan** [comment]
You’ll want to target at least 4.6.1 for compatibility with sharppcap 4.5.0 as 4.6.1 is compatible with .net standard.

**Comment by chmorgan** [comment]
closing as it sounds like you've resolved this
