### ISSUE TITLE
It's not compatible?

### ISSUE THREAD

**Issue by RobbieW69** [chmorgan/sharppcap#44]
Severity	Code	Description	Project	File	Line	Suppression State
Error		Could not install package 'SharpPcap 4.5.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v3.5', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.			0

**Comment by RobbieW69** [comment]
I'm an idiot.

**Comment by RobbieW69** [comment]
What version of the .net framework do I need?

**Comment by chmorgan** [comment]
You’ll want to use either .net framework 4.6.1 or later, or .net standard,
I think 2.0.

Keep in mind that mono is still required for cross platform support on Mac
and Linux. I’m working on fixes for dotnet support on these platforms but
not sure when I’ll get to it.

**Comment by lextm** [comment]
Though most people should have already upgraded to .NET Framework 4.6.1 and above (so .NET Standard 2.0 is not a problem), Microsoft stills supports .NET Framework 4.5.2 and above. It is still ideal to ship a .NET Framework 4.5 compatible assembly.

**Comment by chmorgan** [comment]
@lextm any idea how much work it would be to reenable building for 4.5? I think I upgraded because the Mac visual studio was having issues with the older build target.

**Comment by lextm** [comment]
@chmorgan actually it is quite simple,

* https://github.com/chmorgan/packetnet/pull/89 shows the code change needed.
* Publish a new version of PacketDotNet.
* Then in this repo, update to that PacketDotNet release, and also add net45 to the core project.

No other changes are needed.

**Comment by chmorgan** [comment]
@lextm I merged that net45 target change. Appveyor should auto-build and deploy to nuget but I'm not sure exactly how that might work on the package or deployment side.

**Comment by lextm** [comment]
@chmorgan I am not familiar with AppVeyor deployment. But based on the log https://ci.appveyor.com/project/chmorgan/packetnet/builds/22588493 the generated package is still of version 0.20.0. You might need to bump the version to 0.21.0 to trigger another deployment.

**Comment by chmorgan** [comment]
Ahh right. I’ve been occupied with other tasks. If someone wants to submit
a pr to update the version that would speed things up. Not sure when I’ll
be able to get back to it otherwise.

Chris

**Comment by chmorgan** [comment]
Closing as sharppcap 4.6.0 and new packetdotnet have been released.
