### ISSUE TITLE
Bad SharpPcap.csproj file?

### ISSUE THREAD

**Issue by jmwhitmire** [chmorgan/sharppcap#45]
Downloaded the zip file today.  Loading SharpPcap.sln in VS 2015 loads all the example projects, but the SharpPcap project load fails. Looking at that csproj file, it is only 27 lines and appears to be lacking 95% of what should be in there.
(Also, the sln file says that the minimum VS version is 10, but none of the projects will load in VS version 10.)

**Comment by lextm** [comment]
The project is now SDK based, which means you need .NET Core SDK installed, and compile in VS 2017 and above (or VSCode/Rider). All old VS releases cannot work with such project files.

**Comment by chmorgan** [comment]
@lextm, I didn’t merge your changes in yet but maybe this was a byproduct of changes I made a few months ago?

**Comment by lextm** [comment]
@chmorgan SharpPcap.csproj was converted to SDK based a long time ago, when you attempted to compile against .NET Standard 2.0. So whether my changes in #61 are merged or not, the minimal VS version to compile the current code base should be VS 2017.

**Comment by chmorgan** [comment]
Hi @jmwhitmire, you'll want to use a newer version of visual studio. Let me know if there are any other issues with the project files. I've merged in some great work by @lextm so things should build better now.
