### ISSUE TITLE
TcpPacket Exception

### ISSUE THREAD

**Issue by los93sol** [chmorgan/sharppcap#51]
I occasionally see TcpPacket throw an ArgumentException "Source array was not long enough.  Check the source index, length, and the array's lower bounds." when I attempt to access the PayloadData property.  Interestingly, when I look at the packets that have been received I can tell something went wonky because I suddenly see the AckNumber of the previous few packets showing in the SequenceNumber of the one that ultimately blows up.  Any idea what the cause of this issue could be or what I can look at to get you more information to help me work through it?

**Comment by los93sol** [comment]
Not sure if this helps at all, but one thing I did notice about this is that the ethernet frame length looks abnormal to me, 65549, I was under the impression that 65535 was the longest possible

**Comment by los93sol** [comment]
Did a little more debugging on this and found that the Ethernet frame indicates the data should be 65549 bytes long, but it is e.Packet.Data.Length is only 65536 bytes long so that explains where the exception comes from, but I'm still not sure why it's short.  If there is anything in particular I can test please let me know as I'm able to reliably repro this

**Comment by los93sol** [comment]
I should also probably note I'm using LibPcap.  I'm wondering if this is maybe some native buffer or something.  Is there a way to check that or override it?

**Comment by los93sol** [comment]
Well, I think I found it....

in LibPcapLiveDevice it is opened with.....

                PcapHandle = LibPcapSafeNativeMethods.pcap_open_live
                    (   Name,                   // name of the device
                        Pcap.MAX_PACKET_SIZE,   // portion of the packet to capture. 
                                                // MAX_PACKET_SIZE (65536) grants that the whole packet will be captured on all the MACs.
                        (int)mode,              // promiscuous mode
                        read_timeout,           // read timeout
                        errbuf );               // error buffer

**Comment by los93sol** [comment]
annnnd I take that back yet again, that's exactly where the issue is, the buffer is set there, just a little differently now.  As a test I modified it to 65537 and found that now e.Packet.Data is truncated to a maximum of 65537 instead of 65536

**Comment by los93sol** [comment]
Okay, so after spamming my own thread I believe that the value in Pcap.MAX_PACKET_SIZE is not accounting for the fact that a TCP packet's max length is 65,536, but that can be wrapped in either an IPv4 or IPv6 packet that can also be wrapped in an Ethernet packet so that actual max length is actually 65,549

**Comment by chmorgan** [comment]
Hi @los93sol.

Could you add a tcp test for this large packet size and add the .pcap file? Having a test that fails would make it possible for others to reproduce and when it's fixed we can avoid regressing in supporting large packets.

**Comment by los93sol** [comment]
Yes, I’ll take a look at that and get a PR over to you as soon as I get a chance

**Comment by chmorgan** [comment]
Hi @los93sol I'm closing this one out and looking forward to a pull request if you still plan to submit one.
