### ISSUE TITLE
Trying to build on MacOS -> System.DllNotFoundException has been thrown wpcap

### ISSUE THREAD

**Issue by defcon8** [chmorgan/sharppcap#52]
Hi Guys,

I'm trying to run example 9 - sendpacket. But i'm getting stuck on:

**System.DllNotFoundException has been thrown** wpcap

So as far as i understand i need to do some kind of dynamic library mapping in a sharppcap .config file to define the location of libpcap? But i can't find any example on how to do this.

Can anybody please help me?

Thank you very much!
Bastiaan

<img width="1278" alt="screen shot 2018-07-22 at 21 43 26" src="https://user-images.githubusercontent.com/3636349/43049515-6afb87a0-8df9-11e8-83b4-1dd9634df6c4.png">

**Comment by winkmichael** [comment]
Write SharpPcap.dll.config in the same directory as your runtime, with this;


<configuration>
  <dllmap dll="wpcap" target="libpcap.so.0.8" os="linux" />
  <dllmap dll="wpcap" target="libpcap.dylib"  os="osx"   />
</configuration>

**Comment by chmorgan** [comment]
@defcon8 @winkmichael is correct. Check the examples and the source distribution, there should be an example sharppcap.dll.config file if there isn't one in the binary package.

**Comment by winkmichael** [comment]
https://github.com/antmicro/Packet.Net/blob/master/Examples/SharpPcap.dll.config
