### ISSUE TITLE
Example 11 - Runtime Crash

### ISSUE THREAD

**Issue by winkmichael** [chmorgan/sharppcap#55]
I've tried without much success to run Example 11, in all cases when I run the sample after selecting an input I get;

Unhandled Exception:
System.NullReferenceException: Object reference not set to an instance of an object
  at Example11.WinPcapStatisticsMode.Main (System.String[] args) [0x000d7] in <679e31d55ef4414fae6e8c0290da3a8b>:0 
[ERROR] FATAL UNHANDLED EXCEPTION: System.NullReferenceException: Object reference not set to an instance of an object
  at Example11.WinPcapStatisticsMode.Main (System.String[] args) [0x000d7] in <679e31d55ef4414fae6e8c0290da3a8b>:0

**Comment by chmorgan** [comment]
@winkmichael is this with winpcap or npcap?

**Comment by winkmichael** [comment]
libpcap on Linux and OSX.

**Comment by chmorgan** [comment]
Hi @winkmichael, example 11 is only supported under Windows. I've added a check at the start that will let you know that it isn't supported if your platform isn't windows. Please check out the 4.6.0 release.
