### ISSUE TITLE
No mapping for the Unicode character exists in the target multi-byte code page

### ISSUE THREAD

**Issue by losttem** [chmorgan/sharppcap#58]
When i used in windows server 2012 r2 x64, it throws exception"No mapping for the Unicode character exists in the target multi-byte code page". 
First, i checked .net framework and vc 2010 redistribution, they were all installed well.
At last, i found it was caused by my Chinese language driver because when i replace my network adapter driver by English version, it works well. the network adapter's description is in Chinese if i install Chinese language driver.
if anyone knows any other methods to support interface with Chinese driver?
my network adapter: Intel® Ethernet Server Adapter X520-DA2

**Comment by chmorgan** [comment]
Hi @losttem any thoughts on how to resolve this issue? I don't have a Chinese driver here. If you end up tracking it down I'd appreciate a pull request to resolve.

**Comment by chmorgan** [comment]
Hi @losttem. I'd need a way to reproduce the issue here to debug it. Please reopen if you can provide information on how to reproduce or a code change to resolve.
