### ISSUE TITLE
 IEnumerable<RawCapture> wrapper CaptureFileReaderDevice

### ISSUE THREAD

**Issue by camkego** [chmorgan/sharppcap#6]
I am a heavy Linq and LinqPad user, I repeatedly find my self needing a simple  IEnumerable<RawCapture> wrapper for CaptureFileReaderDevice().

Would the maintainers be interested in seeing either:
1. A pull request for such an enhancement
2. Examples of why this can be so helpful, and sometimes powerful for Linq users ?

Thanks,
Cameron
PS, I am a light Github user, so if there is a better protocol for submitting these types of questions, please forgive me, and let me know how to submit questions or pull requests in the future.

**Comment by chmorgan** [comment]
Merged your branch so closing this one out. Thanks for the pull request!

**Comment by camkego** [comment]
Thanks for taking the contribution and your help getting it just right.


Cameron Elliott
Lime Video Software  206-310-3284
www.limevideo.com
Digital Video SDKs for C# - .NET for Windows - Mono for Linux
