### ISSUE TITLE
System.OverflowException : Arithmetic operation resulted in an overflow.

### ISSUE THREAD

**Issue by lextm** [chmorgan/sharppcap#62]
https://dev.azure.com/lextudio/lextudio/_build/results?buildId=49

As the log shows, on Linux and Mac, the `IntPtr` to `uint` conversion can fail with `OverflowException`.

Should consider changing the data type from `uint` to `long` or `ulong`.

**Comment by chmorgan** [comment]
Good catch. That does look like a bug as IntPtr can be represented as a long or ulong in terms of size depending on platform. Would you be able to open a PR to correct?

**Comment by lextm** [comment]
Implemented the initial fix in 
https://github.com/chmorgan/sharppcap/pull/61/commits/e51a2dc64bfe88177e141a004d76280162472c9e under #61 .

It does suppress the exception, but long to uint conversion might not be ideal. A long term patch might be created in a future pull request.

**Comment by chmorgan** [comment]
Closing this out as I've merged the PR.
