### ISSUE TITLE
Exception on thread abort [dotnet core]

### ISSUE THREAD

**Issue by Meyweridlovaas** [chmorgan/sharppcap#66]
Tested on Raspberry Pi (Linux ARM)

When a device stop its capture (SharpPcap.LibPcap.PcapDevice.StopCapture() , line 208), the capture Thread is joined with a timeout and then aborted if not join, however Thread abort is not supported on dotnet core.

The code I'm running is similar to Example3.BasicCap

![2019-04-19-095318_800x480_scrot](https://user-images.githubusercontent.com/19608628/56419348-35e20000-629a-11e9-82e2-534efcd2a365.png)

It seems to work on Windows in dotnet core, maybe because the Raspberry isn't powerful enough to join the thread quickly ?

**Comment by chmorgan** [comment]
That could be the case. What if you increase the timeout amount? Does it work then?

**Comment by chmorgan** [comment]
Closing due to lack of response.

**Comment by njbrown09** [comment]
Also having this issue

**Comment by samik027** [comment]
Hello, I'm currently experiencing the same problem.

`           device.Open();
            device.StartCapture();

            for (int i = 0; i < ports.Length; i++)
            {
                Sender.sendTCPsynPacket(device, sourcePort, (ushort)ports[i], SrcIP, DstIp, SrcMac);
                Thread.Sleep(20);
            }

            Console.WriteLine("waiting on ACK packets arrival");
            Thread.Sleep(5000);
            device.StopCapture();
            device.Close();`

**Comment by kayoub5** [comment]
@samik027 try the latest code on master

**Comment by samik027** [comment]
Okay, I downloaded the master and managed to create a .dll file through Visual Studio 2019. It does not throw Exception now, but it seems like the capturing is not stopped after the `device.StopCapture()` gets called. The program just doesn't exit and still runs in the background.

**Comment by chmorgan** [comment]
Hi @samik027. This is a known issue and I'm guessing you are seeing it in cases where there is no traffic present, let me explain.

With mono, sharppcap has the ability to retrieve the file descriptors for the device and poll() on the file descriptor with a timeout. This timeout lets sharppcap detect when you've asked the capture to stop even if there isn't any traffic present.

With .net core we call the libpcap function directly. In the case where there is no traffic there is no way to interrupt this call.

There are improvements in libpcap for some time now, maybe end of 2018, that improve this situation but they haven't made it into the 1.9.1 release (the latest release). If there is a newer release it will likely contain these improvements and you'll see the capture thread shut down as expected.

I've pinged the libpcap devs to see if there is anything I or others can do to help move along the release of a new version.

**Comment by chmorgan** [comment]
And @Meyweridlovaas and @njbrown09 see above as well for more details.

**Comment by samik027** [comment]
Thanks for the explanation, @chmorgan!
If I understand correctly, there is no way (at the moment) in .net core to stop the device from capturing if no traffic is present?

**Comment by chmorgan** [comment]
@samik027, correct. I can see if access to the fd is exposed via .net core
but afaik it isn’t.

**Comment by bboelaert** [comment]
Hi,

I'm faced with the same issue. I downloaded the latest version of libpcap (1.10.0-PRE-GIT) and I'm still having this thread abort exception. Any way to work around this?
8:59:13.603 : Receiving ARP reply #4 from sender with MAC address 44:8A:5B:FA:4B:78
8:59:14.600 : Sending ARP request #5 ...
8:59:14.603 : Receiving ARP reply #5 from sender with MAC address 44:8A:5B:FA:4B:78
Stopping packet capture with time-out 00:00:10 ...
Would throw the following exception on stopping the packet capture : Thread abort is not supported on this platform.

Thanks in advance!

**Comment by bboelaert** [comment]
Could threat.Interrupt() be a solution?
See https://stackoverflow.com/questions/53465551/dotnet-core-equivalent-to-thread-abort
