### ISSUE TITLE
System.Runtime.InteropServices.SEHException

### ISSUE THREAD

**Issue by luqide** [chmorgan/sharppcap#70]
when run var devices = AirPcapDeviceList.Instance;
throw System.Runtime.InteropServices.SEHException

**Comment by Wootness** [comment]
I was thrown the same exception a while ago and the problem was with WinPcap.
If you are using windows, did you make sure WinPcap is installed? Did you install Npcap instead?
If you installed Npcap, did you install it in 'WinPcap compatible mode'?

**Comment by chmorgan** [comment]
Airpcap is deprecated. I thought I had removed support for it but maybe not
yet. It’s on the relatively short list as it’s a relatively easy activity.
If someone else is interested in picking it up feel free and open a PR
against it.

**Comment by chmorgan** [comment]
AirPcap support has been removed, closing this issue out.
