### ISSUE TITLE
SharpPcap.LibPcap.LibPcapLiveDevice Unable to activate the adapter

### ISSUE THREAD

**Issue by larswilliam** [chmorgan/sharppcap#71]
The SharpPcap.LibPcap.LibPcapLiveDevice is throwing the "Unable to activate the adapter" following:

var activationResult = LibPcapSafeNativeMethods.pcap_activate(PcapHandle);

using Windows 10 and Npcap 0.995 attempting MonitorMode = Active following:

winPcap.Open(DeviceMode.Promiscuous, readTimeoutMilliseconds, MonitorMode.Active);

The monitor mode works fine when using the Adapter with Wireshark.

**Comment by chmorgan** [comment]
Hello.

Does it work without promiscuous mode?

Chris

**Comment by Blackburn29** [comment]
I am having this same issue with nPcap on windows 10 and also on MacOS. Seems to happen when i set `read_timeout` to anything <= 0.

In regards to your question, promiscuous or normal mode does not make a difference.

**Comment by larswilliam** [comment]
I also got the same exception with DeviceMode.Normal

read_timeout =1000

**Comment by Blackburn29** [comment]
@larswilliam what type of adapter are you trying to listen to? I think I figured this one out to where the adapter has to be active in windows. You may need to see if other devices are listening on the adapter, or maybe give your computer a restart. As for my issue with MacOS, I was able to solve this by setting the timeout to 1ms as I need packets in as close to real-time for my application.

**Comment by larswilliam** [comment]
> Hello.
> 
> Does it work without promiscuous mode?
> 
> Chris
> …

Hi Chris, and many thanks for your excellent and useful work.

No it does not work without promiscuous mode (DeviceMode.Normal).

I have tried using Windows 10.0.17763 and both Npcap 0.993 and 0.995.

I have tried the to install the Npcap both with and without WinPcap API-Compatible Mode.
![Capture_NPCAP_Setup_1](https://user-images.githubusercontent.com/21128660/59554984-fb4fc780-8fab-11e9-9f7a-3e31a5e4285e.GIF)

I have tried using both Alfa AWUS036NEH and Netgear A6210 WiFi USB adapters witch both work as expected with Wireshark when it comes to Monitor Mode.

However, the exception is always thrown like this:

![Exception](https://user-images.githubusercontent.com/21128660/59555046-f0e1fd80-8fac-11e9-87f1-a2afe550991d.GIF)

When stepping into the exception I find this:

![Capture_LibPcapSafeNative](https://user-images.githubusercontent.com/21128660/59555106-ed9b4180-8fad-11e9-9101-27bb87f4c339.GIF)

**Comment by chmorgan** [comment]
Can you provide a list of adapters as reported by Sharppcap and the one reported by Wireshark?

It looks like you are trying to open a remote capture connection, I'm not sure what the constraints on doing so are. Is this the same adapter you are opening on Wireshark?

**Comment by larswilliam** [comment]
Sure 
![Capture_adapter_list_1](https://user-images.githubusercontent.com/21128660/59557326-6662c380-8fd7-11e9-80be-e9fce953b832.GIF)
![Capture_adapter_list_2](https://user-images.githubusercontent.com/21128660/59557330-724e8580-8fd7-11e9-9a39-c19d0f465a8f.GIF)

As you see the adapter list is quite crowded, but it works with Wireshark. For this example I have WinPcap API-Combability mode unchecked and use the brand new Npcap 0.996. As before if fails the same way as mentioned above while Wireshark works ok.

**Comment by larswilliam** [comment]
The reason for the multiple adapters is Hyper-V ;-I

**Comment by chmorgan** [comment]
@larswilliam it might be worth asking the Npcap guys what might be going on. Sharppcap is calling standard apis provided by npcap. The fact that things changed with newer npcap means the library might have changed some behavior or gotten more strict about usage. If its an issue due to an api change we can make changes pretty quickly to accommodate.

**Comment by larswilliam** [comment]
After just reading bmenees comment that he posted 14 days ago at "SharpPcap is not working with latest npcap" I got inspired and rolled back the Npcap to 0.991 I got surprised!

ShapPcap 4.6.1 in combination with Npcap 0.991 works as supposed with monitor mode :-)

**Comment by chmorgan** [comment]
@guyharris I'd like to run this down but if the OP isn't responding I'm inclined to close this out now. How did you spot this btw? ;-)

**Comment by chmorgan** [comment]
@guyharris and how have you been? Not sure if you recall me from some time ago but we've exchanged emails etc from 2014 and earlier.

**Comment by juyanith** [comment]
For what it's worth I am getting the same error. We have an application that opens the device in promiscuous mode for network monitoring. Using wireshark 2.6.x (and winpcap) network capture works properly but if we upgrade to wireshark 3.0 (npcap) we get this same error. Wireshark itself ir able to open the device and capture packets of course. There doesn't seem to be a workaround; I've tried both normal and promiscuous modes and various timeout settings, all with the same error.

**Comment by juyanith** [comment]
I have done some more experimenting and I have found that Example5.PcapFilter.cs shows the same error.

`SharpPcap.PcapException
  HResult=0x80131500
  Message=Unable to activate the adapter (rpcap://\Device\NPF_{...device id here...}). Return code: -1
  Source=SharpPcap
  StackTrace:
   at SharpPcap.LibPcap.LibPcapLiveDevice.Open(DeviceMode mode, Int32 read_timeout, MonitorMode monitor_mode, UInt32 kernel_buffer_size) in C:\sharppcap\SharpPcap\LibPcap\LibPcapLiveDevice.cs:line 281
   at SharpPcap.LibPcap.LibPcapLiveDevice.Open(DeviceMode mode, Int32 read_timeout, UInt32 kernel_buffer_size) in C:\sharppcap\SharpPcap\LibPcap\LibPcapLiveDevice.cs:line 199
   at SharpPcap.LibPcap.LibPcapLiveDevice.Open(DeviceMode mode, Int32 read_timeout) in C:\sharppcap\SharpPcap\LibPcap\LibPcapLiveDevice.cs:line 181
   at Example5.PcapFilter.Main(String[] args) in C:\sharppcap\Examples\Example5.PcapFilter\Example5.PcapFilter.cs:line 50`

Interestingly enough, Example3.BasicCap.cs does not have the error but it has code that checks if the device is a WinPcapDevice and calls its Open method instead:
`            if(device is WinPcapDevice)
            {
                var winPcap = device as WinPcapDevice;
                winPcap.Open(SharpPcap.WinPcap.OpenFlags.DataTransferUdp | SharpPcap.WinPcap.OpenFlags.NoCaptureLocal, readTimeoutMilliseconds);
            }`

**Comment by juyanith** [comment]
Last update for now. I was able to get our code to work by specifically calling WinPcapDevice.Open instead of ICaptureDevice.Open and then updating the ParsePacket call as follows:
Change
`var packet = PacketDotNet.Packet.ParsePacket(e.Packet.LinkLayerType, e.Packet.Data);`
To
`var packet = PacketDotNet.Packet.ParsePacket(LinkLayers.Ethernet, e.Packet.Data);`

The WinPcapDevice always has a LinkLayerType of Null but I know we are looking for ethenet packets. This works for our local application since we are only interested in UDP packets anyway. Maybe this will help track down the larger issue of why simply calling `device.Open(DeviceMode.Promiscuous, ReadTimeout);` causes the error though.

**Comment by guyharris** [comment]
> Using wireshark 2.6.x (and winpcap) network capture works properly but if we upgrade to wireshark 3.0 (npcap) we get this same error.

What happens if you upgrade to Wireshark 3.0.4, which includes the most recent Npcap release, 0.9983?

**Comment by juyanith** [comment]
Sorry, I wasn't clear. The testing I did today was after upgrading to 3.0.4 and 0.9983 from 2.6.11 and winpcap. I also tried going npcap 0.991 but that had different issues (it would not detect adapters). Right now it is working on 0.9983 with the changes that I outlined above but I don't really know why the simple call to ICaptureDevice.Open does not.

**Comment by guyharris** [comment]
> The testing I did today was after upgrading to 3.0.4 and 0.9983 from 2.6.11 and winpcap.

Are you getting a LinkLayerType of Null or Ethernet for the device with 0.9983?  I assume the device is an Ethernet adapter rather than an internal loopback device, as WinPcap didn't offer loopback devices equivalent to the UN\*X loopback device, although Npcap does.

**Comment by juyanith** [comment]
I am getting `e.Packet.LinkLayerType == LinkLayers.Null` using npcap 0.9983 on a network adapter (local network).

**Comment by guyharris** [comment]
Presumably `LinkLayers` is coming from [LinkLayers.cs](https://github.com/antmicro/Packet.Net/blob/master/PacketDotNet/LinkLayers.cs); those are a subset of DLT_ values.

It looks as if the `LibPcap` defines the `LinkType` method, and that `WinPcapDevice` inherits that method.  The `LinkType` appears to come from the result of a call to `pcap_datalink()`, so, for an Ethernet device, it *should* be returning `DLT_EN10MB`/`LinkLayers.Ethernet`, i.e. 1, not `DLT_NULL`/`LinkLayers.Null`, i.e. 0.

If you capture on that same adapter with Wireshark, and you open up the Statistics > Capture File Properties window, what does it report for "Interface" and for "Link type" under "Interfaces"?

**Comment by juyanith** [comment]
Here is the relevant section under Interfaces:
Interface | Dropped packets | Capture filter | Link type | Packet size limit
Ethernet | Unknown | none | Ethernet | 262144 bytes

**Comment by guyharris** [comment]
OK, so Wireshark recognizes it as an Ethernet adapter, so if `e.Packet.LinkLayerType` is returning `LinkLayers.Null`, something weird is happening.

**Comment by chmorgan** [comment]
Hi @juyanith. Is there a possibility to run sharppcap from a source build and print out to the console the pcap_datalink()?

Also, do you see the same behavior if you run your application as admin vs a normal user?

**Comment by juyanith** [comment]
Following your advice to check `pcap_datalink()` I modified WinPcapDevice to print out the value after `pcap_open()` was called. The result was 1, aka Ethernet.

I then started looking for why `PcapDevice.dataLink` was Null and determined that the two `WinPcapDeviceOpen(OpenFlags, ...)` methods do not set the `Active` flag to true. The no parameter `WinPcapDevice.Open()` will set it to true however because it calls the base `LibPcapLiveDevice.Open()` method. Adding `Active = true` ensures that `dataLink` is set properly.

I don't believe I can submit a pull request so I'll attach a diff as it's a pretty small change.

[winpcap_active_not_set.zip](https://github.com/chmorgan/sharppcap/files/3626513/winpcap_active_not_set.zip)

**Comment by juyanith** [comment]
I took the advice @guyharris made earlier in this thread and added some calls to `pcap_statustostr()` and `pcap_geterr()`. The call to `pcap_activate()` now gives a somewhat more informative error message:

> 'Generic error' Error opening adapter: The system cannot find the device specified.  (20)

Unfortunately I'm not sure where to go from here. I'd rather not have to include the type-checking code but explicitly using WinPcapDevice works while LibPcapDevice does not.

**Comment by chmorgan** [comment]
Thank you for that testing and patch. It looks like you’ve found the issue.
I can almost recall when the change was made but want to consult with the
code. I’ll also look at how to use the status error functions to add more
helpful strings to any errors or exceptions thrown.

Should be able to take a look at this today.

Chris

**Comment by chmorgan** [comment]
@juyanith pushed the fix out to master, would you mind giving it a spin? It's the same as your changes, although I did make the edits manually.

**Comment by juyanith** [comment]
@chmorgan I pulled the changes and it fixes the `LinkType` issue in `WinPcapDevice`. Thanks! Any thoughts on what is up with the `LibPcapLiveDevice` issues?

The main thing I've noticed is that they use the library differently. WinPcapDevice calls `SafeNativeMethods.pcap_open()` and LibPcapLiveDevice calls `LibPcapSafeNativeMethods.pcap_create()` followed by `LibPcapSafeNativeMethods.pcap_activate()`. It's that last call that gets the error. It makes me wonder if it is some sort of security policy that is causing the issue.

**Comment by chmorgan** [comment]
@juyanith it could be related to a security policy. I'm not seeing any issues here in my usage, which does tend to be linux though rather than windows. Are you seeing that issue in your current setup that could provide a test case?

**Comment by guyharris** [comment]
> The main thing I've noticed is that they use the library differently. WinPcapDevice calls `SafeNativeMethods.pcap_open()` and LibPcapLiveDevice calls `LibPcapSafeNativeMethods.pcap_create()` followed by `LibPcapSafeNativeMethods.pcap_activate()`. It's that last call that gets the error. It makes me wonder if it is some sort of security policy that is causing the issue.

At least in WinPcap 4.1.3, `pcap_open()` parses the string passed to it to see if it's a URL or not and, if it's not a URL or is a URL that refers to a local device, calls `pcap_open_live()` with the device string.  `pcap_open_live()` calls `pcap_create()`, `pcap_set_snaplen()`, `pcap_set_promisc()`, and `pcap_set_timeout()`, sets an internal flag that only affects the behavior on macOS, and calls `pcap_activate()`.

So it all ends up in `pcap_create()` and `pcap_activate()`, no matter whether you use those routines, `pcap_open_live()`, or `pcap_open()`.

If you're passing a string of the form "rpcap://\Device\NPF_{...device id here...}", that is ***NOT*** supported by any pcap API other than `pcap_open()`, because only `pcap_open()` does the check for a URL and, if it's a URL that refers to a local device, as that one does, strip the URL scheme off and pass that to `pcap_open_live()`.

The extra "rpcap://" doesn't serve a useful purpose; you could just pass "\Device\NPF_{...device id here...}" to all the pcap device-opening APIs and they'd work Just Fine.

**Comment by chmorgan** [comment]
@guyharris the "rpcap://" is appended by npcap but agreed that we don't need that prefix, see https://github.com/chmorgan/sharppcap/issues/78 :-)

**Comment by guyharris** [comment]
> the "rpcap://" is appended by npcap

"Putting the "backward" in "backward compatibility"" - that's what `pcap_findalldevs_ex()` does in WinPcap, and thus what it does in the versions of libpcap that have it, and thus what Npcap does.  It's not there to make any other pcap APIs happy, it's there just in case some program using it expects a URL scheme at the beginning of everything `pcap_findalldevs_ex()` supplies.

I will be *so* happy once I can replace both `pcap_open()` and `pcap_findalldevs_ex()` with new APIs that handle both local and remote capture.

Programs should probably using `pcap_open()` and `pcap_findalldevs_ex()` only when doing remote captures; that, for example, is what tcpdump does.

**Comment by juyanith** [comment]
And sure enough, if I add a hack to remove the "rpcap://" from the name the problem goes away.

**Comment by chmorgan** [comment]
Closing this out as there was a bug in an older npcap version, at least from what I read on the npcap issues list on GitHub, and there were a couple of bugs in Sharppcap around not activating the device. Also we've reduced the scope of pcap_findalldevs_ex() to only the necessary code path so device names should be cleaner for everyone now.

**Comment by Rookian** [comment]
Hi guys! I have the same problem. 

I use npcap 0.9884 and SharpPcap 5.0.0.

When I use npcap 0.991 I dont get any device interfaces. With npcap 09884 I get all device interfaces but receive the error "Unable to activate the adapter" when opening the device.

Any idea? If you need some more information let me know.

**Comment by chmorgan** [comment]
Hi Alex.

Can you try sharppcap from master? This has some fixes to winpcap device
that may resolve the activation issue. If everything looks good I’ll look
to schedule a new version release in the near future.

Regards,
Chris

**Comment by Rookian** [comment]
@chmorgan Yes, this is working!  
You just changed the device name. I created myself a small helper to get the best interface (win32 API) for a given IP address.

Old Code

```
public static ICaptureDevice GetDefaultCaptureDevice(this IPAddress ip)
{
    var nicName = NIC.GetDefaultId(ip);
    var device = CaptureDeviceList.Instance
        .SingleOrDefault(x => x.Name.Replace("rpcap://\\Device\\NPF_", "") == nicName);
    return device;
}
```

New Code  
```
public static ICaptureDevice GetDefaultCaptureDevice(this IPAddress ip)
{
    var nicName = NIC.GetDefaultId(ip);
    var device = CaptureDeviceList.Instance
        .SingleOrDefault(x => x.Name.Replace(@"\Device\NPF_", "") == nicName);
    return device;
}
```

So please ship the new version :bow: :rocket:

**Comment by RodrigoLeiteF** [comment]
Any updates on shipping the new version?

**Comment by chmorgan** [comment]
5.1.0 is pushed to nuget as of yesterday or the day before. This has a
handful of fixes and the npcap namespace and updates packetdotnet and other
dependent assemblies to their latest versions.

Chris

**Comment by kayoub5** [comment]
@dqk0902 create your own issue with detailed context
