### ISSUE TITLE
GetSystem.DllNotFoundException: Unable to load shared library 'libpcap' or one of its dependencies.

### ISSUE THREAD

**Issue by porscheme** [chmorgan/sharppcap#72]
Platform: Alpine docker container (linux) with dotnetcore
Package installed: LibPcap (libpcap.so.1 and libpcap.so.1.8.1)

I'm getting **Unable to load shared library 'libpcap' or one of its dependencies** error.
I'm not sure if I need sharppcap.dll.config file since its not mono project, I had it anyways.
```
 sharppcap.dll.config
-----------------------
<configuration>
  <dllmap dll="wpcap" target="libpcap.so" />
</configuration>
```

```
stack trace
------------
GetSystem.DllNotFoundException: Unable to load shared library 'libpcap' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: Error loading shared library liblibpcap: No such file or directory\n   at SharpPcap.LibPcap.Unix.pcap_findalldevs(IntPtr& alldevs, StringBuilder errbuf)\n   at SharpPcap.LibPcap.LibPcapLiveDeviceList.GetDevices()\n   at SharpPcap.LibPcap.LibPcapLiveDeviceList.Refresh()\n   at SharpPcap.LibPcap.LibPcapLiveDeviceList.get_Instance()\n   at TestWebApp.PacketCapture.GetUniqueNetworkDevice(String devicePartialName) in /app/TestWebApp/LivePackets/PacketCapture.cs:line 96\n   at TestWebApp.Controllers.ValuesController.Get() in /app/TestWebApp/Controllers/ValuesController.cs:line 26"]
```

```
my docker file
---------------
FROM mcr.microsoft.com/dotnet/core/sdk:2.2-alpine AS build
WORKDIR /app
EXPOSE 80
EXPOSE 443

COPY docker.sln .
COPY TestWebApp/TestWebApp.csproj ./TestWebApp/
RUN dotnet restore

COPY TestWebApp/. ./TestWebApp/
WORKDIR /app/TestWebApp
RUN dotnet publish -c Release -o out
					   
FROM mcr.microsoft.com/dotnet/core/aspnet:2.2-alpine AS runtime
WORKDIR /app
COPY --from=build /app/TestWebApp/out ./

RUN rm -rf /var/cache/apk/* && \
    rm -rf /tmp/*

RUN apk update && apk add \
                  bash \
                  grep \
                  build-base \
                  jansson \
                  libcap \
                  libpcap

ENTRYPOINT ["dotnet", "TestWebApp.dll"]
```

**Comment by porscheme** [comment]
GetSystem.DllNotFoundException: Unable to load shared library 'libpcap' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: Error loading shared library liblibpcap: No such file or directory\n   at SharpPcap.LibPcap.Unix.pcap_findalldevs(IntPtr& alldevs, StringBuilder errbuf)\n   at SharpPcap.LibPcap.LibPcapLiveDeviceList.GetDevices()\n   at SharpPcap.LibPcap.LibPcapLiveDeviceList.Refresh()\n   at SharpPcap.LibPcap.LibPcapLiveDeviceList.get_Instance()\n   at Fingerprint.PacketCapture.GetUniqueNetworkDevice(String devicePartialName) in /app/Fingerprint/LivePackets/PacketCapture.cs:line 96\n   at Fingerprint.Controllers.ValuesController.Get() in /app/Fingerprint/Controllers/ValuesController.cs:line 26"]

**Comment by chmorgan** [comment]
Hello. Can you rerun after setting that LD_DEBUG environment variable and re running? I have a few guesses but rather than guess we should look at the debug output to see.

**Comment by porscheme** [comment]
It started working after i created symlink like below.
RUN ln -sf /usr/lib/libpcap.so.1.8.1 /app/libpcap.so

Is creating symlink mandatory even though libpcap was installed in /usr/lib?

Also, I got libpcap.so.1.8.1 by running add libpcap command, is this the latest?

**Comment by chmorgan** [comment]
@porscheme that's exactly what I was thinking in terms of the issue. I can't find any real docs around how library searching works with dotnet. Imo this is a weakness or issue with dotnet. It should be possible to use wildcards (not sure if it is but it doesn't mention it on the msdn page). I'm not sure that this is something we can fix in sharppcap given how DllImport is working. You could always file a bug against it, that would be helpful I think.

**Comment by chmorgan** [comment]
Oh and I'm not sure if 1.8.1 is the latest version or not.

**Comment by sbrl** [comment]
Yeah, I've had several issues like this on Artix Linux. It's not an issue that's specific to Mono, I don't think
