### ISSUE TITLE
How to get 'friendly names' from network adapters

### ISSUE THREAD

**Issue by DamienDaco** [chmorgan/sharppcap#76]
Platform: 
+ Windows 10 Pro
+ Npcap latest version 0.9983
+ .NET Core 2.1

Issue: 
+ Can't get accurate and friendly descriptions for network adapters
+ Can't get accurate number of adapters

Hi, first of all, thank you for your great work.
I'm trying to learn C# and build a GUI driven ARP resolver.
I would like to get a list of my network adapters and display 'friendly names' to my users.
However, using the Description method from SharpPcap:
```
// Retrieve the device list
            var devices = LibPcapLiveDeviceList.Instance;
int i = 0;
            // Print out the available devices
            foreach (var dev in devices)
            {
                Console.WriteLine("{0}) {1}", i, dev.Description);
                i++;
            }
```

This is the output:

> 0) Microsoft Corporation
> 1)
> 2) NdisWan Adapter
> 3) Realtek PCIe GbE Family Controller
> 4) NdisWan Adapter
> 5) NdisWan Adapter
> 6) Adapter for loopback traffic capture

So not only am I getting some duplicate 'NdisWan' descriptions, I am also getting too many of them, and it doesn't reflect what I'm getting from native methods. One of the adapter has no description at all. It makes selecting the right interface a difficult guessing game.

Here's an example, on the same computer, using some native .net methods, this is what I'm looking for:

```
            NetworkInterface[] adapters = NetworkInterface.GetAllNetworkInterfaces();
            foreach (NetworkInterface adapter in adapters)
            {
                    Console.WriteLine("{0}", adapter.Description);
                
            }
```
Output:

>  Realtek PCIe GbE Family Controller
> Npcap Loopback Adapter
> Software Loopback Interface 1
> Hyper-V Virtual Ethernet Adapter

Is there a way I could get a similar list with friendly names (and accurate number of interfaces), using SharpPcap?

**Comment by UweR7** [comment]
Thedevice list comes form NPCAP and not from Sharppcap!
Read this:
https://nmap.org/npcap/guide/npcap-devguide.html#npcap-detect

Means in my opinion is everything fine / no issue.

**Comment by DamienDaco** [comment]
I realize SharpPcap is getting the adapters from WinPCap/NPCap.
I just wanted to know if there was any hope of extracting a more accurate description somehow.

I can't find any solution for that problem; however I managed to check through all Npcap adapters, and select only those who have a valid IPv4 address configured. This isn't perfect (because of poor descriptions) but it works in the end.

Thanks, closing this.

**Comment by chmorgan** [comment]
Imo you should ask the npcap guys and keep this open and link to the
question in their GitHub. They have been super helpful in the past. If they
can provide that info we can hook it up here, or if it goes into the
description field it will just pop out. Npcap is under active development
so it’s possible they can provide feedback on the idea.

Chris
