### ISSUE TITLE
No adapter at all can be opened.

### ISSUE THREAD

**Issue by UweR7** [chmorgan/sharppcap#77]
Hi,
not sure but I believe I found a bug (and hopefully also the solution).
 
My environment:
- Windows 10, Build 17763
- Your latest version from https://github.com/chmorgan/sharppcap 
- https://nmap.org/npcap/dist/npcap-0.9983.exe

Error:
Device list  can be generated, but no adapter at all can be opened.

Reason:
Device name is wrong. 
Device name starts always with “rpcap://” 

Solution:
Removing the string “rpcap://” from  the device.Name solve the issue.

My change (that works for me):
- “WinPcapDeviceList.cs”
adding this single line of code 
 
	pcap_if_unmanaged.Name = pcap_if_unmanaged.Name.Replace(rpcapString, string.Empty);
  
![CodeSnapshot](https://user-images.githubusercontent.com/30627710/64860585-e24bc680-d62d-11e9-9de5-810c76e5b9e1.png)

Please verify and in case you can reproduce fix it ;-)

Thanks in advance.

**Comment by chmorgan** [comment]
HI @UweR7.

Can you help me understand more about what is going on here? If the device name is altered then how is npcap able to know the device is an rpcap device when opening it with a name that lacks the rpcap prefix? Also, it does seem odd that npcap would provide a name with a prefix and then require a lack of that prefix to open the name. Have you reached out to the npcap developers to confirm this behavior is intentional or do the docs specify that it is?

Chris

**Comment by UweR7** [comment]
Hi Chris,

thanks for your very fast reply.

As I said. The found devices were found, but no one could be opened until the prefixed string is removed.
That’s what I figured out.
Why must it be known that the found device is an rpcap device?
What is a rpcap device? What is the difference between a rpcap device and a device built-in in my computer? 😉
My solution works for me. So your question about the lacking prefix seems not to be a problem.
No I don’t reached / asked them.

What do you figured out? Did you tried my “one single line code change”? Does it also work for you?

Brgds,
Uwe

**Comment by chmorgan** [comment]
Hello again.

Can you check with the npcap guys to see why this is the case? If sharppcap
isn’t adding the rpcap prefix then it’s a question of why npcap wouldn’t
ask want that prefix present when opening the device for symmetry. It
provided device named X and it should open device named X no? Otherwise why
not provide the device name without the prefix?

Chris

**Comment by UweR7** [comment]
Please dont get me wrong!


  1.  In case this class is a sharppcap class …
[cid:image001.png@01D56A43.B4F42570]
… Also(?) sharppcap adds under some circumstances the prefix.

  2.  Sorry, but I think you are the right person to ask them
sharppcap is “your” application. You should be responsible to clarify this. It should be in your interest to do so, or?
And: If they ask me one question about your code I would have to forward this question to you.

Thank you in advance.

Brgds,
Uwe

**Comment by chmorgan** [comment]
Hi Uwe.

I develop on Mac and Linux so I wouldn’t be able to easily reproduce your
issue. The npcap guys are friendly. Let me know if you end up finding
anything out. I’d like to fix the issue but we need to make sure it’s the
correct fix first.

Chris

**Comment by UweR7** [comment]
Hi Chris,

istnot a fact of be friendly or not nor whether on which OS you are developing.
Believe me I have no problem also to ask them.
But when I took a closer look to YOUR(?) class WinPcapDeviceList
I figured out that YOU are prefixing th device name.

So the right person is you to ask why the device e name are prefixed 😉

So I am out for the weekend.

Greetings,
Uwe

**Comment by chmorgan** [comment]
Hi @uwer7.

I don't see anywhere where sharppcap is prepending that rpcap prefix. Let me try to test here and discuss with the npcap guys. Appreciate your reporting the issue and a potential fix.

**Comment by chmorgan** [comment]
Hi @UweR7. I'm able to find and see devices with the names prefixed with rpcap:// and they open fine and capture fine as well with Example3. When does this issue occur to you? Can you reproduce and include your output from the console when it doesn't work for you?

I've also confirmed that that prefix is being added by libpcap / npcap, not SharpPcap. It may work when you open it but we can't break remote devices that require the rpcap:// syntax by always stripping it off as you've proposed here.

Now there is a potential improvement in naming that could be done. If we used pcap_findalldevs() we could avoid the rpcap:// prefix you are seeing. This is a nice improvement so I'll open an issue with a potential improvement tag and indicate the source of the issue.

**Comment by UweR7** [comment]
Hi Chris,

I am using/playing around with example 12. But this does not matter.

As said, capturing devices data/info works fine. No issue there. But the device name is prefixed.
This happens here (as I said earlier):
[cid:image002.jpg@01D56AEC.77C65390]
The output does not give an further clue.
Finally it seems to work as you would expected it BUT IN MY case it does NOT work – until I remove the prefix. As shown in the screenshot line 143.

By the way it surprises me that the original device name Property is change by the npcap library.
In my opinion It would be better to let the original (device) name property as read out and add an new specific ncap property which contains the original value prefixed with whatever is needed.
But this should be discussed with them.

Hope I helped.
Bye.

**Comment by chmorgan** [comment]
@UweR7 rpcap prefix issue should be fixed now on master. Please reopen if it isn't!
