### ISSUE TITLE
WinPcap devices are always prefixed with 'rpcap://' even if they are local

### ISSUE THREAD

**Issue by chmorgan** [chmorgan/sharppcap#78]
WinPcapDeviceList.cs uses pcap_findalldevs_ex() to enumerate devices,

https://github.com/chmorgan/sharppcap/blob/master/SharpPcap/WinPcap/WinPcapDeviceList.cs#L123-L126

pcap_findalldevs_ex() requires the device source, which is 'rpcap://' to indicate a remote capture, but without a hostname or port, which indicates a local adapter. This is the way you have to list local devices with pcap_findalldevs_ex(). See the definition of PCAP_SRC_IF_STRING in libpcap,

https://github.com/the-tcpdump-group/libpcap/blob/deb0397995aff5f622a4d0aee9c4b0e505c0b1f7/pcap/pcap.h#L690-L695

A potential fix for those interested, is to refactor:

   private static List<WinPcapDevice> Devices(string rpcapString,
                                                   RemoteAuthentication remoteAuthentication)

such that the core enumeration can be shared between two code paths, one that uses pcap_findalldevs_ex() when an override that takes in a remote server is called, and one that uses pcap_findalldevs() when other overrides without remote server info are called.

**Comment by juyanith** [comment]
@chmorgan  here is a patch for you: [no_rpcap_on_create.zip](https://github.com/chmorgan/sharppcap/files/3628284/no_rpcap_on_create.zip)

Is this what you had in mind?

**Comment by chmorgan** [comment]
@juyanith let me take a look. Btw you should be able to create pull requests, that would make it easier to review.

**Comment by chmorgan** [comment]
@juyanith yeah that patch looks like it does it. Mind submitting as a pr? If its a lot of work I can just apply and push it here.

**Comment by chmorgan** [comment]
@juyanith alright, pushed to master for testing

**Comment by chmorgan** [comment]
@juyanith give me a few more minutes or the next hour or so, I may get interrupted here for a while. I think what you have is close but not the simplest approach. Going to revert master for now.

**Comment by chmorgan** [comment]
@juyanith alright, can you try this branch, https://github.com/chmorgan/sharppcap/tree/winpcapremote

**Comment by juyanith** [comment]
@chmorgan yes that does work. I guess I assumed that calling `WinPcapDeviceList.Devices(rpcapString, null)` would also make use of `pcap_findalldevs()`. I gather that the intent is that the user must call Devices(address, port, remoteAuthentication) to get remote devices; otherwise they always get local devices. That makes sense.

Thanks for your help!

**Comment by chmorgan** [comment]
@juyanith it does look like in case where the path is "" and the auth is null that we *could* make the code call pcap_findalldevs(). It seems like the user should call the other Devices() method though instead. Merging to master now, thanks for the push on this one!
