### ISSUE TITLE
Rename WinPcapDevice to something windows generic or Npcap specific?

### ISSUE THREAD

**Issue by chmorgan** [chmorgan/sharppcap#81]
WinPcap device is deprecated, npcap is maintained, should we rename WinPcapdevice to something more accurate based on what is being used, or maybe windows specific like WinDevice?

**Comment by lextm** [comment]
It can be a bad idea to call NPcapDevice, as what might happen if npcap one day ends up with the same fate? As this library works cross platform, WinDevice is also not good enough. CaptureDevice might be a more generic term.

However, for backward compatibility, you should add new classes (even copying from existing) instead of renaming old ones, as that breaks any code depending on the old classes.

**Comment by chmorgan** [comment]
@lextm I'm open to other ideas for naming the classes. Thoughts? Maybe just Windows?

**Comment by chmorgan** [comment]
@juyanith, @lextm, @hsluoyz any thoughts on the naming of the npcap/windows classes? Should we call them npcap like they are, rename to Windows to reflect the platform which doesn't align with the other libpcap class naming.

**Comment by hsluoyz** [comment]
Why not PcapDevice? All of libpcap, WinPcap, Npcap are Pcap-based technologies.

**Comment by juyanith** [comment]
NPcapDevice matches the new library name. WinPcap is the old library, NPcap is the new one; a naming decision made outside of sharppcap.  
@hsluoyz PcapDevice is already in use as the base implementation of ICaptureDevice for the pcap library. I guess it could be renamed to something like PcapDeviceBase but I think that would be more confusing.
@chmorgan I don't mind using NPcap as that is what the wrapped library is called and I don't think there is a reason to hide this as an implementation detail.

**Comment by hsluoyz** [comment]
Then I think NpcapDevice is good. (Note: it's Npcap instead of NPcap now)

**Comment by chmorgan** [comment]
The reason we haven't folded it into the same CaptureDevice class is that there are additional functions provided by npcap that aren't available from libpcap. @hsluoyz I'm not sure how specific this functionality is today or if it is even necessary today in which case we could consider unifying the two and providing only the api exposed by libpcap. Thoughts?

**Comment by juyanith** [comment]
@hsluoyz Hmmm, you are correct about it being Npcap rather than NPcap. I guess I just assumed the "N" was separate from "Pcap" (like WinPcap). It looks like "LibPcap" should also be "Libpcap" if we are going to match the library names. So "WinPcap" was the oddball all along.

**Comment by chmorgan** [comment]
@juyanith, @hsluoyz, @lextm 

@lextm thank you for providing feedback on the naming issue. There isn't a good way to discuss these kinds of things on GitHub except here in issues and its tough to propose changes and get people to review until they are in. @juyanith thanks for the rename patch, it will continue to be helpful even if I have to make some changes for naming.

I think we need to keep Npcap specific code because there are some differences in api between the two and some users are likely to want to use those features. I'm open to ideas in this area though.

On the topic of naming we are using the library names today. Users *can* use libpcap on windows, Mac and linux, but can only use Npcap on Windows. I'm open to ideas for renaming 

I'm going to look at fixing the issue this weekend. This will involve:

- rebasing master to put the deleted files back and a commit to introduce [Obsolete] messages.
- renaming the new classes to be Npcap and the device name NpcapDevice

Comments, questions?

**Comment by chmorgan** [comment]
Pushed out to master for your review.

**Comment by kayoub5** [comment]
@chmorgan My toughs on this:
The features/API that Npcap/WinPcap provide that are not part of the standard Libpcap API (or have no equivalent API):
* Remote Capture: This could be moved to a RemotePcapDevice and RemotePcapDeviceList, that works independently of the driver used.
* Send Queues, I think should be moved out of Npcap/WinPcap and have two backing implementations, one using the driver API if available, and one fallback implementation, that emulates what the driver does, without the performance gain.
* Statistics Mode: This could be done using a StatisticsPcapDevice wrapper, the wrapper uses the statistics mode of the driver if available, and fallback to counting bytes/packets manually if not.

**Comment by kayoub5** [comment]
@chmorgan I could implement the above proposed changes if you approve the idea.

**Comment by chmorgan** [comment]
@kayoub5 I like the idea of bolting that stuff on to make the api more consistent across the platforms. We would need to make sure we don't break API compatibility until maybe 6.x but that shouldn't stop us from introducing new classes until the other ones are removed. I'd probably do one at a time with tests if possible.

**Comment by chmorgan** [comment]
Closing this one out as we've merged these renames to master.
