### ISSUE TITLE
Add support for Win10PCap library

### ISSUE THREAD

**Issue by knoxi** [chmorgan/sharppcap#88]
Add support for the library [Win10PCap](http://www.win10pcap.org/) since the usage of the free NPCap is [limited to 5 systems](https://github.com/nmap/npcap/blob/master/LICENSE).

**Comment by kayoub5** [comment]
@knoxi WinPcap driver works fine on Windows 10, and Win10Pcap looks dead (latest commit is 4 years ago.)

**Comment by chmorgan** [comment]
@knoxi I have to agree with @kayoub5, the GitHub for win10pcap looks dead. If we added support for it who would maintain our support and the win10pcap library itself? Appreciate the feedback, if there are other capture libraries that make sense to support we'd be interested in hearing about them.
