### ISSUE TITLE
AirPcap is Missing

### ISSUE THREAD

**Issue by orkamar** [chmorgan/sharppcap#89]
Where is the AirPcap code?
the ARCHITECTURE file says that there should be a folder called AirPcap but there isn't.

**Comment by orkamar** [comment]
AirPcap is no longer supported.
Need to update ARCHITECTURE file and SharpPcap/Tutorial/index.html.

**Comment by chmorgan** [comment]
Do you need the airpcap code? It should still be available via an old
release or old code in git.

Regards,
Chris

**Comment by orkamar** [comment]
I downloaded the old code from git.
Thanks,
Or
