### ISSUE TITLE
NoExceptionsWithJustStatisticsHandler Test Fails

### ISSUE THREAD

**Issue by Abdullah2993** [chmorgan/sharppcap#9]
[NoExceptionsWithJustStatisticsHandler](https://github.com/chmorgan/sharppcap/blob/master/Test/WinPcap/WinPcapDeviceTest.cs#L34) test fails with exception

```
SharpPcap.DeviceNotReadyException
No delegates assigned to OnPacketArrival or OnPcapStatistics, no where for captured packets to go.
```

### Reason
The test is to make sure no exception is thrown if OnPcapStatistics event is assigned but you forget to assign the handler so [NoExceptionsWithJustStatisticsHandler](https://github.com/chmorgan/sharppcap/blob/master/Test/WinPcap/WinPcapDeviceTest.cs#L34) and [DeviceNotReadyExceptionWhenStartingACaptureWithoutAddingDelegateToOnPacketArrivalAndOnPcapStatistics](https://github.com/chmorgan/sharppcap/blob/master/Test/WinPcap/WinPcapDeviceTest.cs#L67) are essentially the  same.
### Remedy
just add this line [Here](https://github.com/chmorgan/sharppcap/blob/master/Test/WinPcap/WinPcapDeviceTest.cs#L44)
```
devices[0].OnPcapStatistics += (sender, args) => { };
``` 
### Note
I have configured [AppVeyor](https://appveyor.com) with my [Fork Here](https://github.com/Abdullah2993/sharppcap) and fixed all the build, test and reference issues. You can check the [build status here](https://ci.appveyor.com/project/Abdullah2993/sharppcap).
PS: If you want I can send a pull request with those fixes

**Comment by chmorgan** [comment]
Good catch on that bug. I don't often test on windows so its good to have someone checking that. I'll get that pushed out to master in a minute.

Very cool on AppVeyor. Plan to open pull request to fix the other issues? Small pieces at a time if you could.

**Comment by chmorgan** [comment]
Fix pushed up.
